import type { Locale } from "../locale";

const en: Record<string, string> = {
  "web.check": "The web is the documents and media. The internet is the network that moves the packets.",
  "web.lab": "Listen, accept the TCP connection, read the request, validate it, send 200 with the status file, and close because the client asked.",
  "web.fault": "The network was quiet. The server sent a bad response for a file that exists.",
  "web.leak": "The status line goes to the desk. The key stays in the server environment.",
  "web.close": "HTTP/1.0 with Connection: close means the server closes after this response.",
  "git.check": "Git is the history on the machine. GitHub is a host where you can grant access to that history.",
  "git.lab": "Commit the README and the source on feature/status-404, with a message that names the 404. Leave the secret, the build, and the scratch note out, and leave main where it is.",
  "git.secret": "A live key in a commit is already exposed. Remove it and rotate it.",
  "git.message": "The message should name the change: return 404 when the status path is unknown.",
  "git.branch": "The fix lands on a branch, and main moves only after the checks are green.",
  "devops.check": "DORA uses four numbers: deployment frequency, lead time, change failure rate, and time to restore.",
  "devops.lab": "The unit test is development, the production watch is operations, and the rollback script is automation. This log has four deploys, an 8 hour Tuesday lead, one failure, and a restore of 2 hours 30 minutes.",
  "devops.own": "One person can still trace the failure, restore the service, and write the four numbers.",
  "devops.restore": "Time to restore is from the failed deploy at 18:00 until the service was back at 20:30.",
  "devops.auto": "The rollback should run without someone typing it at night, and the record of the deploy stays.",
  "finops.check": "Model spend is justified when someone uses the result in a decision.",
  "finops.lab": "Cap the idle runners, keep the ledger database, stop the unread summaries, and take the personal transcode off the shared account.",
  "finops.cap": "Cap the idle runners and attribute the minutes to the service. Do not hide the line.",
  "finops.tokens": "Stop the summaries until a person uses them. A larger window does not create a reader.",
  "finops.trust": "Personal work comes off the shared paid account. The account is a trust.",
  "opsbrief.web": "Send 200 with the status file, leave the key out, and close the connection.",
  "opsbrief.git": "Land the fix on a branch, rotate the leaked key, and move main only after the checks are green.",
  "opsbrief.devops": "Record frequency, lead time, failure rate, and time to restore for this release.",
  "opsbrief.finops": "Cap the idle runners and stop the unread summaries.",
};

const es: Record<string, string> = {
  "web.check": "La web son los documentos y los medios. Internet es la red que mueve los paquetes.",
  "web.lab": "Escucha, acepta la conexión TCP, lee la petición, valídala, envía 200 con el archivo de estado y cierra porque el cliente lo pidió.",
  "web.fault": "La red estaba quieta. El servidor envió una mala respuesta para un archivo que existe.",
  "web.leak": "La línea de estado va al mostrador. La clave se queda en el entorno del servidor.",
  "web.close": "HTTP/1.0 con Connection: close significa que el servidor cierra después de esta respuesta.",
  "git.check": "Git es el historial en la máquina. GitHub es un host donde puedes dar acceso a ese historial.",
  "git.lab": "Confirma el README y el código en feature/status-404, con un mensaje que nombra el 404. Deja fuera el secreto, la compilación y la nota, y no muevas main.",
  "git.secret": "Una clave viva en un commit ya está expuesta. Quítala y rótala.",
  "git.message": "El mensaje debe nombrar el cambio: devolver 404 cuando la ruta de estado es desconocida.",
  "git.branch": "El arreglo va a una rama, y main se mueve solo cuando las comprobaciones están en verde.",
  "devops.check": "DORA usa cuatro números: frecuencia de despliegue, tiempo de espera, tasa de fallos y tiempo de restauración.",
  "devops.lab": "La prueba unitaria es desarrollo, vigilar producción es operaciones y el script de reversión es automatización. Este registro tiene cuatro despliegues, 8 horas de espera el martes, un fallo y una restauración de 2 horas y 30 minutos.",
  "devops.own": "Una persona puede seguir el fallo, restaurar el servicio y anotar los cuatro números.",
  "devops.restore": "El tiempo de restauración va del despliegue fallido a las 18:00 hasta el servicio recuperado a las 20:30.",
  "devops.auto": "La reversión debe ejecutarse sin que alguien la escriba de noche, y el registro del despliegue permanece.",
  "finops.check": "El gasto en un modelo se justifica cuando alguien usa el resultado en una decisión.",
  "finops.lab": "Limita los runners ociosos, conserva la base del libro, detén los resúmenes sin lectores y saca la transcodificación personal de la cuenta compartida.",
  "finops.cap": "Limita los runners ociosos y atribuye los minutos al servicio. No escondas la línea.",
  "finops.tokens": "Detén los resúmenes hasta que una persona los use. Una ventana más grande no crea un lector.",
  "finops.trust": "El trabajo personal sale de la cuenta de pago compartida. La cuenta es una confianza.",
  "opsbrief.web": "Envía 200 con el archivo de estado, sin la clave, y cierra la conexión.",
  "opsbrief.git": "Lleva el arreglo a una rama, rota la clave filtrada y mueve main solo con las comprobaciones en verde.",
  "opsbrief.devops": "Anota frecuencia, tiempo de espera, tasa de fallos y tiempo de restauración de esta publicación.",
  "opsbrief.finops": "Limita los runners ociosos y detén los resúmenes sin lectores.",
};

const fr: Record<string, string> = {
  "web.check": "Le web, ce sont les documents et les médias. Internet est le réseau qui déplace les paquets.",
  "web.lab": "Écouter, accepter la connexion TCP, lire la requête, la valider, envoyer 200 avec le fichier d'état, puis fermer parce que le client l'a demandé.",
  "web.fault": "Le réseau était calme. Le serveur a envoyé une mauvaise réponse pour un fichier qui existe.",
  "web.leak": "La ligne d'état va au guichet. La clé reste dans l'environnement du serveur.",
  "web.close": "HTTP/1.0 avec Connection: close veut dire que le serveur ferme après cette réponse.",
  "git.check": "Git est l'historique sur la machine. GitHub est un hôte où l'on peut donner accès à cet historique.",
  "git.lab": "Validez le README et le source sur feature/status-404, avec un message qui nomme le 404. Laissez dehors le secret, la construction et le brouillon, et ne bougez pas main.",
  "git.secret": "Une clé active dans un commit est déjà exposée. Retirez-la et faites-la tourner.",
  "git.message": "Le message doit nommer le changement : renvoyer 404 quand le chemin d'état est inconnu.",
  "git.branch": "Le correctif arrive sur une branche, et main ne bouge qu'après des contrôles verts.",
  "devops.check": "DORA utilise quatre nombres : fréquence de déploiement, délai, taux d'échec et temps de rétablissement.",
  "devops.lab": "Le test unitaire est du développement, la veille de production est des opérations, et le script de retour arrière est de l'automatisation. Ce journal a quatre déploiements, un délai de 8 heures mardi, un échec, et un rétablissement de 2 heures 30.",
  "devops.own": "Une personne peut encore suivre la panne, rétablir le service et écrire les quatre nombres.",
  "devops.restore": "Le temps de rétablissement va du déploiement raté à 18:00 jusqu'au service rétabli à 20:30.",
  "devops.auto": "Le retour arrière doit tourner sans que quelqu'un le tape la nuit, et la trace du déploiement reste.",
  "finops.check": "La dépense d'un modèle est justifiée quand quelqu'un utilise le résultat dans une décision.",
  "finops.lab": "Plafonnez les runners inactifs, gardez la base du grand livre, arrêtez les résumés sans lecteurs, et retirez le transcodage personnel du compte partagé.",
  "finops.cap": "Plafonnez les runners inactifs et attribuez les minutes au service. Ne cachez pas la ligne.",
  "finops.tokens": "Arrêtez les résumés jusqu'à ce qu'une personne s'en serve. Une fenêtre plus grande ne crée pas un lecteur.",
  "finops.trust": "Le travail personnel quitte le compte payant partagé. Ce compte est une confiance.",
  "opsbrief.web": "Envoyez 200 avec le fichier d'état, sans la clé, et fermez la connexion.",
  "opsbrief.git": "Posez le correctif sur une branche, faites tourner la clé exposée, et ne bougez main qu'après des contrôles verts.",
  "opsbrief.devops": "Notez la fréquence, le délai, le taux d'échec et le temps de rétablissement de cette mise en service.",
  "opsbrief.finops": "Plafonnez les runners inactifs et arrêtez les résumés sans lecteurs.",
};

const de: Record<string, string> = {
  "web.check": "Das Web sind die Dokumente und Medien. Das Internet ist das Netz, das die Pakete bewegt.",
  "web.lab": "Lauschen, die TCP-Verbindung annehmen, die Anfrage lesen, sie prüfen, 200 mit der Statusdatei senden und schließen, weil der Client das verlangt.",
  "web.fault": "Das Netz war ruhig. Der Server hat eine schlechte Antwort für eine Datei geschickt, die existiert.",
  "web.leak": "Die Statuszeile geht an den Schalter. Der Schlüssel bleibt in der Umgebung des Servers.",
  "web.close": "HTTP/1.0 mit Connection: close heißt, der Server schließt nach dieser Antwort.",
  "git.check": "Git ist die Geschichte auf der Maschine. GitHub ist ein Host, auf dem Sie Zugriff auf diese Geschichte geben können.",
  "git.lab": "Committen Sie README und Quelltext auf feature/status-404, mit einer Nachricht, die den 404 nennt. Lassen Sie Geheimnis, Build und Notiz draußen, und lassen Sie main stehen.",
  "git.secret": "Ein aktiver Schlüssel in einem Commit ist schon offengelegt. Entfernen Sie ihn und tauschen Sie ihn aus.",
  "git.message": "Die Nachricht soll die Änderung nennen: 404 zurückgeben, wenn der Statuspfad unbekannt ist.",
  "git.branch": "Die Korrektur landet auf einem Branch, und main bewegt sich erst nach grünen Prüfungen.",
  "devops.check": "DORA nutzt vier Zahlen: Deployment-Häufigkeit, Vorlaufzeit, Fehlerrate und Wiederherstellungszeit.",
  "devops.lab": "Der Unit-Test ist Entwicklung, die Produktionswacht ist Betrieb, das Rollback-Skript ist Automatisierung. Dieses Protokoll hat vier Deployments, 8 Stunden Vorlauf am Dienstag, einen Fehler und 2 Stunden 30 Wiederherstellung.",
  "devops.own": "Eine Person kann den Fehler noch verfolgen, den Dienst wiederherstellen und die vier Zahlen aufschreiben.",
  "devops.restore": "Die Wiederherstellungszeit läuft vom fehlgeschlagenen Deployment um 18:00 bis zum Dienst um 20:30.",
  "devops.auto": "Das Rollback soll laufen, ohne dass es nachts jemand tippt, und die Aufzeichnung des Deployments bleibt.",
  "finops.check": "Ausgaben für ein Modell sind gerechtfertigt, wenn jemand das Ergebnis in einer Entscheidung nutzt.",
  "finops.lab": "Decken Sie ungenutzte Runner, behalten Sie die Ledger-Datenbank, stoppen Sie ungelesene Zusammenfassungen und nehmen Sie die private Transkodierung vom gemeinsamen Konto.",
  "finops.cap": "Decken Sie die ungenutzten Runner und ordnen Sie die Minuten dem Dienst zu. Verstecken Sie die Zeile nicht.",
  "finops.tokens": "Stoppen Sie die Zusammenfassungen, bis eine Person sie nutzt. Ein größeres Fenster schafft keinen Leser.",
  "finops.trust": "Private Arbeit verlässt das gemeinsame bezahlte Konto. Das Konto ist ein Vertrauen.",
  "opsbrief.web": "Senden Sie 200 mit der Statusdatei, ohne Schlüssel, und schließen Sie die Verbindung.",
  "opsbrief.git": "Legen Sie die Korrektur auf einen Branch, tauschen Sie den geleakten Schlüssel und bewegen Sie main erst nach grünen Prüfungen.",
  "opsbrief.devops": "Notieren Sie Häufigkeit, Vorlauf, Fehlerrate und Wiederherstellungszeit dieser Veröffentlichung.",
  "opsbrief.finops": "Decken Sie die ungenutzten Runner und stoppen Sie die ungelesenen Zusammenfassungen.",
};

const pt: Record<string, string> = {
  "web.check": "A web são os documentos e a mídia. A internet é a rede que move os pacotes.",
  "web.lab": "Escute, aceite a conexão TCP, leia o pedido, valide-o, envie 200 com o arquivo de estado e feche porque o cliente pediu.",
  "web.fault": "A rede estava quieta. O servidor enviou uma resposta ruim para um arquivo que existe.",
  "web.leak": "A linha de estado vai ao balcão. A chave fica no ambiente do servidor.",
  "web.close": "HTTP/1.0 com Connection: close significa que o servidor fecha depois desta resposta.",
  "git.check": "Git é o histórico na máquina. O GitHub é um host onde você pode conceder acesso a esse histórico.",
  "git.lab": "Faça o commit do README e do código em feature/status-404, com uma mensagem que nomeia o 404. Deixe de fora o segredo, o build e o rascunho, e não mova o main.",
  "git.secret": "Uma chave ativa num commit já está exposta. Remova-a e gire-a.",
  "git.message": "A mensagem deve nomear a mudança: retornar 404 quando o caminho de estado é desconhecido.",
  "git.branch": "A correção cai num ramo, e o main só se move depois das verificações verdes.",
  "devops.check": "A DORA usa quatro números: frequência de implantação, lead time, taxa de falha e tempo de restauração.",
  "devops.lab": "O teste de unidade é desenvolvimento, vigiar a produção é operação, e o script de retorno é automação. Este registo tem quatro implantações, 8 horas de lead na terça, uma falha e uma restauração de 2 horas e 30 minutos.",
  "devops.own": "Uma pessoa ainda pode seguir a falha, restaurar o serviço e escrever os quatro números.",
  "devops.restore": "O tempo de restauração vai da implantação falhada às 18:00 até o serviço de volta às 20:30.",
  "devops.auto": "O retorno deve correr sem alguém digitá-lo à noite, e o registo da implantação fica.",
  "finops.check": "O gasto com um modelo se justifica quando alguém usa o resultado numa decisão.",
  "finops.lab": "Limite os runners ociosos, mantenha a base do livro, pare os resumos sem leitores e tire a transcodificação pessoal da conta compartilhada.",
  "finops.cap": "Limite os runners ociosos e atribua os minutos ao serviço. Não esconda a linha.",
  "finops.tokens": "Pare os resumos até uma pessoa usá-los. Uma janela maior não cria um leitor.",
  "finops.trust": "O trabalho pessoal sai da conta paga compartilhada. A conta é uma confiança.",
  "opsbrief.web": "Envie 200 com o arquivo de estado, sem a chave, e feche a conexão.",
  "opsbrief.git": "Ponha a correção num ramo, gire a chave vazada e mova o main só depois das verificações verdes.",
  "opsbrief.devops": "Registe frequência, lead time, taxa de falha e tempo de restauração desta publicação.",
  "opsbrief.finops": "Limite os runners ociosos e pare os resumos sem leitores.",
};

const zh: Record<string, string> = {
  "web.check": "Web 是文档和媒体。互联网是运送分组的网络。",
  "web.lab": "先监听，接受 TCP 连接，读请求，校验，用状态文件回复 200，再按客户端的要求关闭连接。",
  "web.fault": "网络是安静的。服务器对一个存在的文件给了错误的响应。",
  "web.leak": "状态行给到柜台。密钥留在服务器的环境里。",
  "web.close": "HTTP/1.0 且 Connection: close，表示这次响应之后服务器关闭连接。",
  "git.check": "Git 是机器上的历史。GitHub 是你可以授权别人访问这段历史的主机。",
  "git.lab": "把 README 和源码提交到 feature/status-404，消息要写明 404。密钥、构建产物和草稿留下，main 不动。",
  "git.secret": "活密钥进了提交就已经暴露。删掉它，并轮换密钥。",
  "git.message": "消息要写出改了什么：状态路径未知时返回 404。",
  "git.branch": "修复先落在分支上，检查变绿之后 main 才移动。",
  "devops.check": "DORA 用四个数：部署频率、前置时间、变更失败率和恢复时间。",
  "devops.lab": "单元测试是开发，看生产错误率是运维，回滚脚本是自动化。这份日志有四次部署，周二前置 8 小时，一次失败，恢复用了 2 小时 30 分。",
  "devops.own": "一个人仍然可以追踪故障、恢复服务，并写下这四个数。",
  "devops.restore": "恢复时间是从 18:00 失败的部署到 20:30 服务恢复。",
  "devops.auto": "回滚应当自己跑，不必有人在夜里敲命令，部署记录要留下。",
  "finops.check": "模型花费合理，是因为有人把结果用进了一个决定。",
  "finops.lab": "给闲置的运行器封顶，留下账本数据库，停掉没人读的摘要，把个人转码移出共享账户。",
  "finops.cap": "给闲置运行器封顶，并把分钟记到这个服务上。不要把这一行藏起来。",
  "finops.tokens": "停掉摘要，直到有人用它做决定。更大的上下文窗口不会变出一个读者。",
  "finops.trust": "个人事务离开共享的付费账户。这个账户是一份信任。",
  "opsbrief.web": "用状态文件回复 200，不要带密钥，并关闭连接。",
  "opsbrief.git": "修复落在分支上，轮换已泄露的密钥，检查变绿之后才移动 main。",
  "opsbrief.devops": "记下这次发布的频率、前置时间、失败率和恢复时间。",
  "opsbrief.finops": "给闲置运行器封顶，并停掉没人读的摘要。",
};

const ja: Record<string, string> = {
  "web.check": "ウェブは文書とメディアです。インターネットはパケットを運ぶネットワークです。",
  "web.lab": "待ち受け、TCP 接続を受け、要求を読み、確かめ、状態ファイルで 200 を返し、クライアントの求めどおり接続を閉じます。",
  "web.fault": "ネットワークは静かでした。あるファイルに対して、サーバーが悪い応答を返しました。",
  "web.leak": "状態の一行は窓口へ。鍵はサーバーの環境に残します。",
  "web.close": "HTTP/1.0 で Connection: close なら、この応答のあとサーバーは接続を閉じます。",
  "git.check": "Git はマシン上の履歴です。GitHub は、その履歴へのアクセスを渡せるホストです。",
  "git.lab": "README とソースを feature/status-404 に、404 を名指すメッセージでコミットします。秘密、ビルド、下書きは入れず、main は動かしません。",
  "git.secret": "生きた鍵がコミットに入った時点で露出しています。取り除き、鍵を回します。",
  "git.message": "メッセージは変更を名指します。状態のパスが未知なら 404 を返す、です。",
  "git.branch": "修正はブランチへ。main は検査が緑になってから動きます。",
  "devops.check": "DORA は四つの数です。デプロイ頻度、リード時間、変更失敗率、復旧時間。",
  "devops.lab": "単体テストは開発、本番の監視は運用、ロールバックのスクリプトは自動化です。このログはデプロイ四回、火曜のリード 8 時間、失敗一回、復旧は 2 時間 30 分です。",
  "devops.own": "一人でも、失敗を追い、サービスを戻し、四つの数を書けます。",
  "devops.restore": "復旧時間は、18:00 の失敗したデプロイから 20:30 にサービスが戻るまでです。",
  "devops.auto": "ロールバックは、夜に誰かが打たなくても動き、デプロイの記録は残します。",
  "finops.check": "モデルへの支払いは、誰かが結果を決定に使ったときに意味があります。",
  "finops.lab": "遊んでいるランナーは上限を設け、台帳のデータベースは残し、読まれない要約は止め、個人の変換は共有アカウントから外します。",
  "finops.cap": "遊んでいるランナーに上限を設け、その分をサービスに帰属させます。行を隠しません。",
  "finops.tokens": "誰かが使うまで要約を止めます。窓を大きくしても読者は生まれません。",
  "finops.trust": "個人の仕事は共有の有料アカウントから外します。そのアカウントは信頼です。",
  "opsbrief.web": "状態ファイルで 200 を返し、鍵は入れず、接続を閉じます。",
  "opsbrief.git": "修正はブランチへ。漏れた鍵は回し、検査が緑になってから main を動かします。",
  "opsbrief.devops": "このリリースの頻度、リード時間、失敗率、復旧時間を記録します。",
  "opsbrief.finops": "遊んでいるランナーに上限を設け、読まれない要約を止めます。",
};

const ar: Record<string, string> = {
  "web.check": "الويب هو الوثائق والوسائط. الإنترنت هو الشبكة التي تنقل الرزم.",
  "web.lab": "استمع، اقبل اتصال TCP، اقرأ الطلب، تحقق منه، أرسل 200 مع ملف الحالة، ثم أغلق لأن العميل طلب ذلك.",
  "web.fault": "كانت الشبكة هادئة. أرسل الخادم استجابة سيئة لملف موجود.",
  "web.leak": "سطر الحالة يذهب إلى المكتب. يبقى المفتاح في بيئة الخادم.",
  "web.close": "HTTP/1.0 مع Connection: close يعني أن الخادم يغلق بعد هذه الاستجابة.",
  "git.check": "Git هو التاريخ على الجهاز. GitHub مضيف تمنح عليه الوصول إلى ذلك التاريخ.",
  "git.lab": "أودع README والمصدر على feature/status-404 برسالة تسمي 404. أبق السر والبناء والمسودة خارجا، واترك main مكانه.",
  "git.secret": "مفتاح حي داخل إيداع مكشوف بالفعل. أزله وبدّله.",
  "git.message": "ينبغي أن تسمي الرسالة التغيير: أعد 404 حين يكون مسار الحالة مجهولا.",
  "git.branch": "يصل الإصلاح إلى فرع، ولا يتحرك main إلا بعد فحوصات خضراء.",
  "devops.check": "تستخدم DORA أربعة أرقام: تكرار النشر، ومدة الانتظار، ومعدل الفشل، ووقت الاستعادة.",
  "devops.lab": "اختبار الوحدة تطوير، ومراقبة الإنتاج تشغيل، ونص التراجع أتمتة. في هذا السجل أربعة نشرات، وثماني ساعات انتظار يوم الثلاثاء، وفشل واحد، واستعادة ساعتين ونصف.",
  "devops.own": "يستطيع شخص واحد أن يتتبع الفشل ويستعيد الخدمة ويكتب الأرقام الأربعة.",
  "devops.restore": "وقت الاستعادة من النشر الفاشل عند 18:00 حتى عودة الخدمة عند 20:30.",
  "devops.auto": "ينبغي أن يعمل التراجع من غير أن يكتبه أحد ليلا، ويبقى سجل النشر.",
  "finops.check": "يبرَّر الإنفاق على نموذج حين يستخدم شخص النتيجة في قرار.",
  "finops.lab": "ضع سقفا للمنفذين الخاملين، وأبق قاعدة الدفتر، وأوقف الملخصات غير المقروءة، وأخرج التحويل الشخصي من الحساب المشترك.",
  "finops.cap": "ضع سقفا للمنفذين الخاملين وانسب الدقائق إلى الخدمة. لا تخف السطر.",
  "finops.tokens": "أوقف الملخصات حتى يستخدمها شخص. نافذة أكبر لا تصنع قارئا.",
  "finops.trust": "يخرج العمل الشخصي من الحساب المدفوع المشترك. الحساب أمانة.",
  "opsbrief.web": "أرسل 200 مع ملف الحالة، من غير المفتاح، وأغلق الاتصال.",
  "opsbrief.git": "ضع الإصلاح على فرع، وبدّل المفتاح المسرب، ولا تحرك main إلا بعد فحوصات خضراء.",
  "opsbrief.devops": "سجّل التكرار ومدة الانتظار ومعدل الفشل ووقت الاستعادة لهذه النشرة.",
  "opsbrief.finops": "ضع سقفا للمنفذين الخاملين وأوقف الملخصات غير المقروءة.",
};

const lines: Record<Locale, Record<string, string>> = { en, es, fr, de, pt, zh, ja, ar };

export function explainOps(locale: Locale, id: string): string {
  return lines[locale]?.[id] ?? lines.en[id] ?? "";
}
