import type { Locale } from "../locale";

const en: Record<string, string> = {
  "tools.check": "Version history lets two people change the same work without one of them erasing the other.",
  "tools.bench": "Name the job, open the shared workbench, make one small change, save it with a reason, and show a colleague.",
  "tools.where": "The clinic's work belongs on a shared workbench, not on one laptop that goes home at night.",
  "tools.memory": "The history remembers each saved change, so the team does not have to trust one person's memory.",
  "tools.fail": "If a check fails, stop, and do not put that failed change on the desk where people will use it.",
  "platforms.check": "The screen can change from one platform to another, but the record and its rules stay the same.",
  "platforms.bench": "The rider uses a phone, the inspector a handheld, and the night desk a keyboard screen, all on one record.",
  "platforms.rider": "A rider between stops needs a phone page, not a trip back to the office.",
  "platforms.same": "What stays the same is the one pass record and its rules, not the colour of each screen.",
  "platforms.avoid": "Keep one record behind every door, because three databases will start to disagree.",
  "design.check": "Design the person's task first, before colour, a logo, or the shape of the database.",
  "design.bench": "Ask one question at a time, and always leave a clear way back.",
  "design.first": "Begin with the task in the person's own words, not with a colour or a logo.",
  "design.error": "Say what went wrong and the next action, and keep the answers they already gave.",
  "design.access": "A person using only a keyboard, including someone new or tired, must still be able to finish.",
  "tiers.check": "The decision about what a person may do lives in the application, where the rules run.",
  "tiers.bench": "The browser shows, the application decides, and the database remembers.",
  "tiers.allowed": "Whether this person may act is decided in the application, with the other rules.",
  "tiers.remember": "What must still be there in the morning is remembered in the database.",
  "tiers.public": "If the deciding room is down, say the board is unavailable instead of inventing an answer.",
  "integration.check": "Red means do not continue: the change is not ready to join the shared work.",
  "integration.bench": "Make the change, run the checklist, let a second person look, and only then merge.",
  "integration.night": "Block a red change, so the morning opens on the last version that was green.",
  "integration.who": "The author and a second person both look, and only after the checklist is green.",
  "integration.secret": "Secrets do not belong in the log, even when the checklist itself is green.",
  "deployment.check": "A release needs a way back, already known, before the change goes in front of people.",
  "deployment.bench": "Change one ward first, and rehearse the return before you go any further.",
  "deployment.size": "Start with one ward, not the whole hospital at once.",
  "deployment.back": "The way back is rehearsed, so a person on the night shift can start it.",
  "deployment.tell": "Tell the nurses and the coordinator, in plain words, what changed and how to go back.",
  "maintain.check": "A new person should be able to change one piece without breaking the rest.",
  "maintain.bench": "Split the thank-you letter from the payment, and leave a written map of which piece is which.",
  "maintain.letter": "Keep the letter apart from the payment, so a change of words cannot touch the money.",
  "maintain.owner": "A named role takes the night call, not a crowd and not nobody.",
  "maintain.words": "The map is written down, so the next person does not have to rebuild it from memory.",
  "scale.check": "What was promised exactly stays exact, such as charging a person only once.",
  "scale.bench": "Protect one ticket and one charge first; a prettier page can wait.",
  "scale.first": "On a busy night, one ticket and one charge must stay exact.",
  "scale.line": "Use a queue with a clear waiting state, so a crowd does not knock over the room that decides.",
  "scale.cache": "A public hint may be a few seconds old, but a payment may not.",
  "observe.check": "When someone says it failed, you need the path of that one request.",
  "observe.bench": "One request is a trace, how many is a metric, and what was written is a log.",
  "observe.night": "Follow that one update from the tap to the record, instead of rebooting and hoping.",
  "observe.alert": "An alert names the action and the role that takes it, not just a noise.",
  "observe.quiet": "Do not page a person for one slow picture.",
  "security.check": "Authentication is who you are; authorisation is what you may do.",
  "security.bench": "A shared password, grades sitting in the address, and a backup on a laptop are the leaks.",
  "security.who": "Each person has their own login, so you can tell who acted.",
  "security.grades": "A student sees their own work, a teacher sees their own class, and the office sees the job it has.",
  "security.leak": "A backup of private records stays locked to a named role, not on a laptop that goes home.",
  "futures.check": "Tools may change, but the promise to the person does not go out of date.",
  "futures.bench": "You may change tools, and you refuse a choice you cannot leave.",
  "futures.keep": "The catalogue stays readable without the vendor, because the record belongs to you.",
  "futures.prepare": "Test a way to leave before you depend on the new door.",
  "futures.refuse": "Do not put the only copy in a service you cannot leave.",
  "brief.tools": "Harbor Market staff work on a shared workbench with a history, not on one laptop that goes home.",
  "brief.platforms": "The shopper, the stallholder, and the office are three doors onto one stall record.",
  "brief.design": "Design the task first: what is open tonight, and who may say so.",
  "brief.tiers": "Whether this person may edit this stall is decided in the application, not only in the browser.",
  "brief.integration": "A red checklist is blocked, and the market opens on the last green version.",
  "brief.deployment": "Release a small change to the public board, with a rehearsed way back.",
  "brief.maintain": "Keep the public words apart from anything that must stay exact, and leave a map.",
  "brief.scale": "On a crowded night the record of a change, and any payment, stays exact.",
  "brief.observe": "When a save fails, follow the path of that one request.",
  "brief.security": "The stallholder sees their own stall, and the office role sees the job it is there to do.",
  "brief.futures": "A new door is welcome only if Harbor Market can leave it and still keep the record.",
};

const es: Record<string, string> = {
  "tools.check": "El historial deja que dos personas cambien el mismo trabajo sin que una borre a la otra.",
  "tools.bench": "Di el trabajo, abre el banco compartido, haz un solo cambio pequeño, guárdalo con el porqué y enséñaselo a un colega.",
  "tools.where": "El trabajo de la clínica vive en un banco compartido, no en un portátil que se va a casa por la noche.",
  "tools.memory": "El historial recuerda cada cambio guardado, así que el equipo no depende de la memoria de una sola persona.",
  "tools.fail": "Si una comprobación falla, se para, y ese cambio no llega al mostrador donde la gente lo va a usar.",
  "platforms.check": "La pantalla puede cambiar de una plataforma a otra, pero el registro y sus reglas siguen iguales.",
  "platforms.bench": "Quien viaja usa un teléfono, quien inspecciona un aparato de mano y el escritorio de noche una pantalla con teclado, todos sobre el mismo registro.",
  "platforms.rider": "Quien viaja entre paradas necesita una página de teléfono, no una vuelta a la oficina.",
  "platforms.same": "Lo que permanece igual es el registro único del pase y sus reglas, no el color de cada pantalla.",
  "platforms.avoid": "Un solo registro detrás de todas las puertas, porque tres bases de datos van a contradecirse.",
  "design.check": "Diseña primero la tarea de la persona, antes del color, del logo o de la forma de la base de datos.",
  "design.bench": "Una pregunta cada vez, y siempre un camino claro para volver.",
  "design.first": "Empieza por la tarea en las palabras de la persona, no por un color ni por un logo.",
  "design.error": "Di qué falló y la acción siguiente, y conserva las respuestas que ya dio.",
  "design.access": "Quien usa solo el teclado, aunque sea nuevo o esté cansado, tiene que poder terminar.",
  "tiers.check": "La decisión de lo que una persona puede hacer vive en la aplicación, donde corren las reglas.",
  "tiers.bench": "El navegador muestra, la aplicación decide y la base de datos recuerda.",
  "tiers.allowed": "Si esta persona puede actuar se decide en la aplicación, junto con las demás reglas.",
  "tiers.remember": "Lo que tiene que seguir ahí por la mañana se recuerda en la base de datos.",
  "tiers.public": "Si la sala que decide está caída, di que el tablón no está disponible, en lugar de inventar una respuesta.",
  "integration.check": "Rojo quiere decir que no se sigue: el cambio todavía no puede unirse al trabajo compartido.",
  "integration.bench": "Haz el cambio, pasa la lista, que mire una segunda persona, y solo entonces se une.",
  "integration.night": "Un cambio en rojo se bloquea, y la mañana abre con la última versión que estaba en verde.",
  "integration.who": "Quien lo escribe y una segunda persona miran, y solo después de que la lista esté en verde.",
  "integration.secret": "Los secretos no pertenecen al registro de la lista, aunque esa lista esté en verde.",
  "deployment.check": "Una publicación necesita un camino de vuelta, ya conocido, antes de poner el cambio delante de la gente.",
  "deployment.bench": "Cambia primero una planta, y ensaya el regreso antes de seguir.",
  "deployment.size": "Empieza por una planta, no por todo el hospital a la vez.",
  "deployment.back": "El camino de vuelta está ensayado, para que alguien de la noche pueda empezarlo.",
  "deployment.tell": "Díselo a las enfermeras y a la coordinación, en palabras llanas: qué cambió y cómo volver.",
  "maintain.check": "Una persona nueva tiene que poder cambiar una pieza sin romper el resto.",
  "maintain.bench": "Separa la carta de agradecimiento del pago, y deja un mapa escrito de qué pieza es cuál.",
  "maintain.letter": "La carta queda aparte del pago, para que un cambio de palabras no toque el dinero.",
  "maintain.owner": "La llamada de noche la recibe un rol con nombre: ni una multitud ni nadie.",
  "maintain.words": "El mapa está escrito, para que la persona siguiente no lo reconstruya de memoria.",
  "scale.check": "Lo prometido con exactitud sigue exacto, como cobrar a una persona una sola vez.",
  "scale.bench": "Protege primero una entrada y un cobro; una página más bonita puede esperar.",
  "scale.first": "En una noche de mucha gente, una entrada y un cobro tienen que seguir exactos.",
  "scale.line": "Usa una cola con un estado de espera claro, para que la multitud no tire la sala que decide.",
  "scale.cache": "Una pista pública puede tener unos segundos de retraso; un pago, no.",
  "observe.check": "Cuando alguien dice que falló, hace falta el camino de esa única petición.",
  "observe.bench": "Una petición es un rastro, cuántas es una métrica, y lo escrito es un registro.",
  "observe.night": "Sigue esa única actualización desde el toque hasta el registro, en lugar de reiniciar y esperar.",
  "observe.alert": "La alerta nombra la acción y el rol que la hace, y no solo hace ruido.",
  "observe.quiet": "No llames a una persona por una sola imagen lenta.",
  "security.check": "La autenticación es quién eres; la autorización es lo que puedes hacer.",
  "security.bench": "Una contraseña compartida, las notas dentro de la dirección y una copia en un portátil son las fugas.",
  "security.who": "Cada persona tiene su propio acceso, para saber quién actuó.",
  "security.grades": "El estudiante ve lo suyo, el docente ve su clase y la oficina ve el trabajo que le toca.",
  "security.leak": "La copia de los registros privados queda cerrada para un rol con nombre, no en un portátil que se va a casa.",
  "futures.check": "Las herramientas pueden cambiar, pero la promesa a la persona no caduca.",
  "futures.bench": "Puedes cambiar de herramientas, y rechazas una elección de la que no puedes salir.",
  "futures.keep": "El catálogo sigue siendo legible sin el proveedor, porque el registro no le pertenece.",
  "futures.prepare": "Prueba un camino de salida antes de depender de la puerta nueva.",
  "futures.refuse": "No pongas la única copia en un servicio del que no puedes salir.",
  "brief.tools": "El personal de Harbor Market trabaja en un banco compartido con historial, no en un portátil que se va a casa.",
  "brief.platforms": "Quien compra, quien tiene el puesto y la oficina son tres puertas sobre un solo registro.",
  "brief.design": "Diseña primero la tarea: qué está abierto esta noche y quién puede decirlo.",
  "brief.tiers": "Si esta persona puede editar este puesto se decide en la aplicación, no solo en el navegador.",
  "brief.integration": "Una lista en rojo se bloquea, y el mercado abre con la última versión en verde.",
  "brief.deployment": "Publica un cambio pequeño en el tablón, con un camino de vuelta ensayado.",
  "brief.maintain": "Las palabras públicas quedan aparte de lo que debe seguir exacto, y queda un mapa.",
  "brief.scale": "En una noche llena, el registro de un cambio y cualquier pago siguen exactos.",
  "brief.observe": "Si un guardado falla, sigue el camino de esa única petición.",
  "brief.security": "Quien tiene el puesto ve el suyo, y el rol de la oficina ve el trabajo para el que está.",
  "brief.futures": "Una puerta nueva solo vale si Harbor Market puede dejarla y conservar el registro.",
};

const fr: Record<string, string> = {
  "tools.check": "L'historique permet à deux personnes de changer le même travail sans que l'une efface l'autre.",
  "tools.bench": "Nomme le travail, ouvre le banc partagé, fais un seul petit changement, enregistre-le avec le pourquoi, et montre-le à un collègue.",
  "tools.where": "Le travail de la clinique vit sur un banc partagé, pas sur un ordinateur portable qui rentre à la maison le soir.",
  "tools.memory": "L'historique se souvient de chaque changement enregistré, pour que l'équipe ne dépende pas de la mémoire d'une seule personne.",
  "tools.fail": "Si une vérification échoue, on s'arrête, et ce changement raté ne va pas sur le comptoir où les gens vont l'utiliser.",
  "platforms.check": "L'écran peut changer d'une plateforme à l'autre, mais l'enregistrement et ses règles restent les mêmes.",
  "platforms.bench": "Le voyageur utilise un téléphone, l'inspecteur un appareil de poche, et le bureau de nuit un écran avec clavier, tous sur un seul enregistrement.",
  "platforms.rider": "Un voyageur entre deux arrêts a besoin d'une page de téléphone, pas d'un retour au bureau.",
  "platforms.same": "Ce qui reste identique, c'est l'enregistrement unique du passe et ses règles, pas la couleur de chaque écran.",
  "platforms.avoid": "Un seul enregistrement derrière toutes les portes, parce que trois bases de données finiront par se contredire.",
  "design.check": "On conçoit d'abord la tâche de la personne, avant la couleur, le logo ou la forme de la base.",
  "design.bench": "Une question à la fois, et toujours un chemin clair pour revenir en arrière.",
  "design.first": "On commence par la tâche, dans les mots de la personne, pas par une couleur ou un logo.",
  "design.error": "On dit ce qui a échoué et l'action suivante, et on garde les réponses déjà données.",
  "design.access": "Quelqu'un qui n'a que le clavier, même nouveau ou fatigué, doit pouvoir finir.",
  "tiers.check": "La décision de ce qu'une personne peut faire vit dans l'application, là où les règles s'exécutent.",
  "tiers.bench": "Le navigateur montre, l'application décide, et la base de données se souvient.",
  "tiers.allowed": "Savoir si cette personne a le droit d'agir se décide dans l'application, avec les autres règles.",
  "tiers.remember": "Ce qui doit encore être là le matin est gardé dans la base de données.",
  "tiers.public": "Si la salle qui décide est arrêtée, on dit que le tableau n'est pas disponible, au lieu d'inventer une réponse.",
  "integration.check": "Rouge veut dire qu'on ne continue pas : le changement n'est pas prêt à rejoindre le travail partagé.",
  "integration.bench": "On change, on passe la liste, une deuxième personne regarde, et seulement alors on fusionne.",
  "integration.night": "Un changement rouge est bloqué, et le matin s'ouvre sur la dernière version verte.",
  "integration.who": "L'auteur et une deuxième personne regardent, et seulement après que la liste est verte.",
  "integration.secret": "Les secrets n'ont pas leur place dans le journal, même si la liste elle-même est verte.",
  "deployment.check": "Une mise en service a besoin d'un chemin pour revenir, déjà connu, avant que le changement arrive devant les gens.",
  "deployment.bench": "On change d'abord une seule unité, et on répète le retour avant d'aller plus loin.",
  "deployment.size": "On commence par une seule unité, pas par tout l'hôpital d'un coup.",
  "deployment.back": "Le retour est répété, pour qu'une personne de nuit puisse le lancer.",
  "deployment.tell": "On le dit clairement aux infirmières et à la coordination : ce qui a changé, et comment revenir.",
  "maintain.check": "Une personne nouvelle doit pouvoir changer une pièce sans casser le reste.",
  "maintain.bench": "On sépare la lettre de remerciement du paiement, et on laisse un plan écrit de quelle pièce est laquelle.",
  "maintain.letter": "La lettre reste à part du paiement, pour qu'un changement de mots ne touche pas l'argent.",
  "maintain.owner": "L'appel de nuit revient à un rôle nommé : ni à une foule, ni à personne.",
  "maintain.words": "Le plan est écrit, pour que la personne suivante n'ait pas à le reconstruire de mémoire.",
  "scale.check": "Ce qui a été promis exactement reste exact, comme ne faire payer une personne qu'une fois.",
  "scale.bench": "On protège d'abord un billet et un paiement ; une page plus jolie peut attendre.",
  "scale.first": "Dans une nuit chargée, un billet et un paiement doivent rester exacts.",
  "scale.line": "Une file, avec un état d'attente clair, pour que la foule ne renverse pas la salle qui décide.",
  "scale.cache": "Un indice public peut avoir quelques secondes de retard ; un paiement, non.",
  "observe.check": "Quand quelqu'un dit que cela a échoué, il faut le chemin de cette seule demande.",
  "observe.bench": "Une demande est une trace, le nombre est une métrique, et ce qui a été écrit est un journal.",
  "observe.night": "On suit cette seule mise à jour, du geste jusqu'à l'enregistrement, au lieu de redémarrer en espérant.",
  "observe.alert": "Une alerte nomme l'action et le rôle qui la fait, au lieu de faire seulement du bruit.",
  "observe.quiet": "On ne réveille pas une personne pour une seule image lente.",
  "security.check": "L'authentification, c'est qui vous êtes ; l'autorisation, c'est ce que vous avez le droit de faire.",
  "security.bench": "Un mot de passe partagé, des notes dans l'adresse de la page, et une sauvegarde sur un portable sont les fuites.",
  "security.who": "Chaque personne a son propre identifiant, pour savoir qui a agi.",
  "security.grades": "L'élève voit son travail, l'enseignant voit sa classe, et le bureau voit la tâche qui lui revient.",
  "security.leak": "La sauvegarde des dossiers privés reste fermée pour un rôle nommé, pas sur un portable qui rentre à la maison.",
  "futures.check": "Les outils peuvent changer ; la promesse faite à la personne ne se périme pas.",
  "futures.bench": "On peut changer d'outils, et on refuse un choix qu'on ne peut pas quitter.",
  "futures.keep": "Le catalogue reste lisible sans le fournisseur, parce que l'enregistrement ne lui appartient pas.",
  "futures.prepare": "On teste une sortie avant de dépendre de la nouvelle porte.",
  "futures.refuse": "On ne met pas la seule copie dans un service qu'on ne peut pas quitter.",
  "brief.tools": "Le personnel de Harbor Market travaille sur un banc partagé avec un historique, pas sur un portable qui rentre à la maison.",
  "brief.platforms": "L'acheteur, le tenant de l'étal et le bureau sont trois portes sur un seul enregistrement.",
  "brief.design": "On conçoit d'abord la tâche : qu'est-ce qui est ouvert ce soir, et qui a le droit de le dire.",
  "brief.tiers": "Savoir si cette personne peut modifier cet étal se décide dans l'application, pas seulement dans le navigateur.",
  "brief.integration": "Une liste rouge est bloquée, et le marché ouvre sur la dernière version verte.",
  "brief.deployment": "On publie un petit changement sur le tableau, avec un retour déjà répété.",
  "brief.maintain": "Les mots publics restent à part de ce qui doit rester exact, avec un plan.",
  "brief.scale": "Dans une nuit pleine, l'enregistrement d'un changement, et tout paiement, restent exacts.",
  "brief.observe": "Si un enregistrement échoue, on suit le chemin de cette seule demande.",
  "brief.security": "Le tenant voit son étal, et le rôle du bureau voit le travail pour lequel il est là.",
  "brief.futures": "Une nouvelle porte n'est acceptable que si Harbor Market peut la quitter et garder l'enregistrement.",
};

const de: Record<string, string> = {
  "tools.check": "Die Versionsgeschichte lässt zwei Menschen dieselbe Arbeit ändern, ohne dass einer den anderen auslöscht.",
  "tools.bench": "Die Aufgabe benennen, die gemeinsame Werkbank öffnen, eine kleine Änderung machen, sie mit einem Warum speichern und einer zweiten Person zeigen.",
  "tools.where": "Die Arbeit der Klinik gehört auf eine gemeinsame Werkbank, nicht auf einen Laptop, der abends nach Hause geht.",
  "tools.memory": "Die Geschichte merkt sich jede gespeicherte Änderung, damit das Team sich nicht auf das Gedächtnis einer Person verlassen muss.",
  "tools.fail": "Wenn eine Prüfung scheitert, anhalten und die gescheiterte Änderung nicht auf den Tresen legen, wo Menschen sie benutzen.",
  "platforms.check": "Der Bildschirm darf sich von Plattform zu Plattform ändern, der Datensatz und seine Regeln bleiben gleich.",
  "platforms.bench": "Fahrgäste nutzen ein Telefon, die Kontrolle ein Handgerät und der Nachtschalter einen Bildschirm mit Tastatur, alle auf einem Datensatz.",
  "platforms.rider": "Unterwegs braucht die fahrende Person eine Telefonseite, nicht einen Weg zurück ins Büro.",
  "platforms.same": "Gleich bleibt der eine Fahrausweis und seine Regeln, nicht die Farbe jedes Bildschirms.",
  "platforms.avoid": "Ein Datensatz hinter allen Türen, denn drei Datenbanken werden sich widersprechen.",
  "design.check": "Zuerst die Aufgabe der Person entwerfen, vor Farbe, Logo oder der Form der Datenbank.",
  "design.bench": "Eine Frage nach der anderen, und immer einen klaren Weg zurück.",
  "design.first": "Mit der Aufgabe in den Worten der Person beginnen, nicht mit einer Farbe oder einem Logo.",
  "design.error": "Sagen, was schiefging und was als Nächstes zu tun ist, und die schon gegebenen Antworten behalten.",
  "design.access": "Auch jemand Neues oder Müdes muss die Aufgabe nur mit der Tastatur zu Ende bringen können.",
  "tiers.check": "Die Entscheidung, was eine Person tun darf, lebt in der Anwendung, wo die Regeln laufen.",
  "tiers.bench": "Der Browser zeigt, die Anwendung entscheidet, und die Datenbank merkt sich.",
  "tiers.allowed": "Ob diese Person handeln darf, entscheidet die Anwendung, zusammen mit den anderen Regeln.",
  "tiers.remember": "Was am Morgen noch da sein muss, merkt sich die Datenbank.",
  "tiers.public": "Wenn der Raum, der entscheidet, ausfällt, sagt die Tafel, dass sie nicht verfügbar ist, statt eine Antwort zu erfinden.",
  "integration.check": "Rot heißt, nicht weiterzugehen: Die Änderung ist noch nicht bereit, zur gemeinsamen Arbeit zu stoßen.",
  "integration.bench": "Zuerst die Änderung, dann die Checkliste, dann eine zweite Person, und erst danach zusammenführen.",
  "integration.night": "Eine rote Änderung wird blockiert, damit der Morgen die letzte grüne Fassung öffnet.",
  "integration.who": "Wer geschrieben hat und eine zweite Person schauen hin, und erst nachdem die Checkliste grün ist.",
  "integration.secret": "Geheimnisse gehören nicht ins Protokoll, auch wenn die Checkliste selbst grün ist.",
  "deployment.check": "Eine Veröffentlichung braucht einen bekannten Weg zurück, bevor die Änderung vor Menschen kommt.",
  "deployment.bench": "Zuerst eine Station ändern, und die Rückkehr proben, bevor es weitergeht.",
  "deployment.size": "Mit einer Station beginnen, nicht mit dem ganzen Krankenhaus auf einmal.",
  "deployment.back": "Der Weg zurück ist geprobt, damit eine Person in der Nachtschicht ihn starten kann.",
  "deployment.tell": "Den Pflegekräften und der Koordination in klaren Worten sagen, was sich geändert hat und wie man zurückgeht.",
  "maintain.check": "Eine neue Person soll ein Stück ändern können, ohne den Rest zu zerbrechen.",
  "maintain.bench": "Den Dankesbrief von der Zahlung trennen und einen aufgeschriebenen Plan dalassen, welches Stück welches ist.",
  "maintain.letter": "Der Brief bleibt getrennt von der Zahlung, damit eine Wortänderung das Geld nicht berührt.",
  "maintain.owner": "Eine benannte Rolle nimmt den Anruf in der Nacht an: nicht eine Menge, und nicht niemand.",
  "maintain.words": "Der Plan ist aufgeschrieben, damit die nächste Person ihn nicht aus dem Gedächtnis neu bauen muss.",
  "scale.check": "Was genau versprochen wurde, bleibt genau, zum Beispiel eine Person nur einmal zu belasten.",
  "scale.bench": "Zuerst ein Ticket und eine Zahlung schützen; eine hübschere Seite kann warten.",
  "scale.first": "In einer vollen Nacht müssen ein Ticket und eine Zahlung genau bleiben.",
  "scale.line": "Eine Warteschlange mit einem klaren Wartezustand, damit die Menge den Raum, der entscheidet, nicht umwirft.",
  "scale.cache": "Ein öffentlicher Hinweis darf ein paar Sekunden alt sein; eine Zahlung nicht.",
  "observe.check": "Wenn jemand sagt, es sei gescheitert, braucht es den Weg dieser einen Anfrage.",
  "observe.bench": "Eine Anfrage ist eine Spur, die Anzahl ist eine Kennzahl, und das Geschriebene ist ein Protokoll.",
  "observe.night": "Dieser einen Aktualisierung folgen, vom Tippen bis zum Datensatz, statt neu zu starten und zu hoffen.",
  "observe.alert": "Ein Alarm nennt die Handlung und die Rolle, die sie ausführt, und nicht nur einen Lärm.",
  "observe.quiet": "Für ein einziges langsames Bild wird kein Mensch gerufen.",
  "security.check": "Authentifizierung ist, wer jemand ist; Autorisierung ist, was diese Person tun darf.",
  "security.bench": "Ein gemeinsames Passwort, Noten in der Adresse und eine Sicherung auf einem Laptop sind die Lecks.",
  "security.who": "Jede Person hat eine eigene Anmeldung, damit sichtbar ist, wer gehandelt hat.",
  "security.grades": "Lernende sehen die eigene Arbeit, Lehrkräfte die eigene Klasse, und das Büro die Aufgabe, die es hat.",
  "security.leak": "Eine Sicherung privater Daten bleibt für eine benannte Rolle verschlossen, nicht auf einem Laptop, der nach Hause geht.",
  "futures.check": "Werkzeuge dürfen sich ändern, das Versprechen an die Person wird nicht ungültig.",
  "futures.bench": "Werkzeuge darf man wechseln, und eine Wahl, die man nicht verlassen kann, lehnt man ab.",
  "futures.keep": "Der Katalog bleibt ohne den Anbieter lesbar, weil die Aufzeichnung nicht ihm gehört.",
  "futures.prepare": "Einen Weg nach draußen prüfen, bevor man von der neuen Tür abhängt.",
  "futures.refuse": "Die einzige Kopie nicht in einen Dienst legen, den man nicht verlassen kann.",
  "brief.tools": "Das Personal von Harbor Market arbeitet an einer gemeinsamen Werkbank mit Geschichte, nicht an einem Laptop, der nach Hause geht.",
  "brief.platforms": "Wer einkauft, wer den Stand hat und das Büro sind drei Türen zu einem einzigen Datensatz des Standes.",
  "brief.design": "Zuerst die Aufgabe entwerfen: Was ist heute Abend offen, und wer darf das sagen.",
  "brief.tiers": "Ob diese Person diesen Stand ändern darf, entscheidet die Anwendung, nicht nur der Browser.",
  "brief.integration": "Eine rote Checkliste wird blockiert, und der Markt öffnet mit der letzten grünen Fassung.",
  "brief.deployment": "Eine kleine Änderung an der öffentlichen Tafel, mit einem geprobten Weg zurück.",
  "brief.maintain": "Die öffentlichen Worte bleiben getrennt von allem, was genau bleiben muss, und es gibt einen Plan.",
  "brief.scale": "In einer vollen Nacht bleiben die Aufzeichnung einer Änderung und jede Zahlung genau.",
  "brief.observe": "Wenn ein Speichern scheitert, dem Weg dieser einen Anfrage folgen.",
  "brief.security": "Wer den Stand hat, sieht den eigenen Stand, und die Rolle des Büros sieht die Aufgabe, für die sie da ist.",
  "brief.futures": "Eine neue Tür ist nur willkommen, wenn Harbor Market sie verlassen und die Aufzeichnung behalten kann.",
};

const pt: Record<string, string> = {
  "tools.check": "O histórico deixa duas pessoas mudarem o mesmo trabalho sem uma apagar a outra.",
  "tools.bench": "Diga o trabalho, abra a bancada compartilhada, faça uma mudança pequena, salve com o porquê e mostre a um colega.",
  "tools.where": "O trabalho da clínica fica numa bancada compartilhada, não num laptop que vai para casa à noite.",
  "tools.memory": "O histórico lembra cada mudança salva, para a equipe não depender da memória de uma só pessoa.",
  "tools.fail": "Se uma verificação falha, pare e não ponha essa mudança falha no balcão, onde as pessoas vão usá-la.",
  "platforms.check": "A tela pode mudar de uma plataforma para outra, mas o registro e as regras continuam os mesmos.",
  "platforms.bench": "Quem viaja usa um celular, quem fiscaliza um aparelho de mão, e a mesa da noite uma tela com teclado, todos no mesmo registro.",
  "platforms.rider": "Quem viaja entre paradas precisa de uma página no celular, não de uma volta ao escritório.",
  "platforms.same": "O que permanece igual é o registro único do passe e as regras dele, não a cor de cada tela.",
  "platforms.avoid": "Um só registro atrás de todas as portas, porque três bancos de dados vão discordar.",
  "design.check": "Desenhe primeiro a tarefa da pessoa, antes da cor, do logotipo ou da forma do banco de dados.",
  "design.bench": "Uma pergunta de cada vez, e sempre um caminho claro de volta.",
  "design.first": "Comece pela tarefa nas palavras da pessoa, não por uma cor ou um logotipo.",
  "design.error": "Diga o que deu errado e a próxima ação, e guarde as respostas que a pessoa já deu.",
  "design.access": "Quem usa só o teclado, mesmo sendo novo ou estando cansado, ainda precisa conseguir terminar.",
  "tiers.check": "A decisão sobre o que uma pessoa pode fazer vive na aplicação, onde as regras rodam.",
  "tiers.bench": "O navegador mostra, a aplicação decide, e o banco de dados lembra.",
  "tiers.allowed": "Se esta pessoa pode agir é decidido na aplicação, junto com as outras regras.",
  "tiers.remember": "O que precisa continuar lá de manhã fica lembrado no banco de dados.",
  "tiers.public": "Se a sala que decide está fora, diga que o quadro não está disponível, em vez de inventar uma resposta.",
  "integration.check": "Vermelho quer dizer não continuar: a mudança ainda não está pronta para entrar no trabalho compartilhado.",
  "integration.bench": "Faça a mudança, rode a lista, uma segunda pessoa olha, e só então se junta.",
  "integration.night": "Bloqueie uma mudança vermelha, para a manhã abrir na última versão que estava verde.",
  "integration.who": "Quem escreve e uma segunda pessoa olham, e só depois de a lista estar verde.",
  "integration.secret": "Segredos não entram no registro da lista, mesmo quando a lista está verde.",
  "deployment.check": "Uma publicação precisa de um caminho de volta, já conhecido, antes de a mudança ir para a frente das pessoas.",
  "deployment.bench": "Mude uma ala primeiro, e ensaie a volta antes de ir adiante.",
  "deployment.size": "Comece por uma ala, não pelo hospital inteiro de uma vez.",
  "deployment.back": "O caminho de volta está ensaiado, para uma pessoa do turno da noite poder começá-lo.",
  "deployment.tell": "Diga à enfermagem e à coordenação, em palavras claras, o que mudou e como voltar.",
  "maintain.check": "Uma pessoa nova precisa poder mudar uma peça sem quebrar o resto.",
  "maintain.bench": "Separe a carta de agradecimento do pagamento, e deixe um mapa escrito de qual peça é qual.",
  "maintain.letter": "A carta fica separada do pagamento, para uma mudança de palavras não tocar no dinheiro.",
  "maintain.owner": "Uma função com nome recebe a chamada da noite: nem uma multidão, nem ninguém.",
  "maintain.words": "O mapa está escrito, para a próxima pessoa não ter de reconstruí-lo de memória.",
  "scale.check": "O que foi prometido com exatidão continua exato, como cobrar uma pessoa uma só vez.",
  "scale.bench": "Proteja primeiro um ingresso e uma cobrança; uma página mais bonita pode esperar.",
  "scale.first": "Numa noite cheia, um ingresso e uma cobrança precisam continuar exatos.",
  "scale.line": "Use uma fila com um estado de espera claro, para a multidão não derrubar a sala que decide.",
  "scale.cache": "Uma dica pública pode estar alguns segundos atrasada; um pagamento, não.",
  "observe.check": "Quando alguém diz que falhou, é preciso o caminho daquele único pedido.",
  "observe.bench": "Um pedido é um rastro, quantos é uma métrica, e o que foi escrito é um registro.",
  "observe.night": "Siga aquela única atualização, do toque até o registro, em vez de reiniciar e esperar.",
  "observe.alert": "Um alerta nomeia a ação e a função que a executa, e não só faz barulho.",
  "observe.quiet": "Não chame uma pessoa por uma única imagem lenta.",
  "security.check": "Autenticação é quem você é; autorização é o que você pode fazer.",
  "security.bench": "Uma senha compartilhada, notas dentro do endereço da página e uma cópia num laptop são os vazamentos.",
  "security.who": "Cada pessoa tem o próprio acesso, para se saber quem agiu.",
  "security.grades": "O estudante vê o próprio trabalho, o professor vê a própria turma, e o escritório vê a tarefa que lhe cabe.",
  "security.leak": "A cópia dos registros privados fica trancada para uma função com nome, não num laptop que vai para casa.",
  "futures.check": "As ferramentas podem mudar, mas a promessa à pessoa não envelhece.",
  "futures.bench": "Você pode trocar de ferramentas, e recusa uma escolha da qual não consegue sair.",
  "futures.keep": "O catálogo continua legível sem o fornecedor, porque o registro não é dele.",
  "futures.prepare": "Teste um caminho de saída antes de depender da porta nova.",
  "futures.refuse": "Não ponha a única cópia num serviço do qual você não consegue sair.",
  "brief.tools": "A equipe do Harbor Market trabalha numa bancada compartilhada com histórico, não num laptop que vai para casa.",
  "brief.platforms": "Quem compra, quem tem a banca e o escritório são três portas para um só registro da banca.",
  "brief.design": "Desenhe primeiro a tarefa: o que está aberto esta noite, e quem pode dizer isso.",
  "brief.tiers": "Se esta pessoa pode editar esta banca é decidido na aplicação, não só no navegador.",
  "brief.integration": "Uma lista vermelha é bloqueada, e o mercado abre na última versão verde.",
  "brief.deployment": "Publique uma mudança pequena no quadro público, com um caminho de volta ensaiado.",
  "brief.maintain": "As palavras públicas ficam separadas de tudo o que precisa continuar exato, com um mapa.",
  "brief.scale": "Numa noite cheia, o registro de uma mudança, e qualquer pagamento, continua exato.",
  "brief.observe": "Quando um salvamento falha, siga o caminho daquele único pedido.",
  "brief.security": "Quem tem a banca vê a própria banca, e a função do escritório vê o trabalho para o qual está ali.",
  "brief.futures": "Uma porta nova só serve se o Harbor Market puder deixá-la e ainda ficar com o registro.",
};

const zh: Record<string, string> = {
  "tools.check": "版本历史让两个人改同一份工作，而不会互相抹掉。",
  "tools.bench": "先说出要做的事，打开共享工作台，做一处小改动，写下为什么再保存，然后给同事看。",
  "tools.where": "诊所的工作放在共享工作台，不放在晚上带回家的那一台笔记本电脑上。",
  "tools.memory": "历史会记住每一次保存的改动，团队不必只靠一个人的记忆。",
  "tools.fail": "检查失败就停下，不要把这次失败的改动放到大家会使用的台面上。",
  "platforms.check": "屏幕可以从一个平台换到另一个，记录和规则保持不变。",
  "platforms.bench": "乘客用手机，查票员用手持设备，夜班用带键盘的桌面，看的是同一份记录。",
  "platforms.rider": "在站与站之间的乘客需要一个手机页面，而不是跑回办公室。",
  "platforms.same": "保持不变的是这一份乘车记录和它的规则，不是每块屏幕的颜色。",
  "platforms.avoid": "所有门后面只留一份记录，因为三套数据库会开始互相矛盾。",
  "design.check": "先设计这个人要完成的任务，再考虑颜色、标志或数据库的形状。",
  "design.bench": "一次只问一个问题，并且始终留一条回去的路。",
  "design.first": "从当事人自己的话里的任务开始，而不是从颜色或标志开始。",
  "design.error": "说明哪里错了、下一步做什么，并保留他们已经填写的答案。",
  "design.access": "只用键盘的人，包括刚来的或疲倦的人，也必须能够做完。",
  "tiers.check": "一个人可以做什么，这个决定放在应用程序里，规则在那里运行。",
  "tiers.bench": "浏览器负责显示，应用程序负责决定，数据库负责记住。",
  "tiers.allowed": "这个人能不能做，由应用程序和其他规则一起决定。",
  "tiers.remember": "到了早上还必须在的内容，记在数据库里。",
  "tiers.public": "做决定的那一间停了，就说明告示板不可用，不要编造一个答案。",
  "integration.check": "红色的意思是不要继续：这次改动还不能并入共享的工作。",
  "integration.bench": "先改动，再跑检查清单，第二个人看过，然后才合并。",
  "integration.night": "挡住红色的改动，早上就用上一次绿色的版本。",
  "integration.who": "作者和第二个人都要看，而且要在检查清单变绿之后。",
  "integration.secret": "秘密不属于日志，哪怕检查清单本身是绿色的。",
  "deployment.check": "发布之前就要有一条已经知道的退路，再把改动放到人们面前。",
  "deployment.bench": "先改一个病区，并把退回去的步骤排练好，再继续扩大。",
  "deployment.size": "先从一个病区开始，不要一次改整个医院。",
  "deployment.back": "退路已经排练过，夜班的人可以自己启动。",
  "deployment.tell": "用明白的话告诉护士和协调员：改了什么，以及怎样退回去。",
  "maintain.check": "新来的人应该能够改一块，而不弄坏其余的部分。",
  "maintain.bench": "把感谢信和付款分开，并留下一张写明各块是什么的地图。",
  "maintain.letter": "信和付款分开，改措辞就不会碰到钱。",
  "maintain.owner": "夜里的电话由一个有名字的角色来接，不是一群人，也不是没有人。",
  "maintain.words": "地图要写下来，下一个人不必靠记忆重新拼出来。",
  "scale.check": "答应要精确的事就保持精确，比如只向一个人收一次费。",
  "scale.bench": "先保住一张票和一次收费；更好看的页面可以等。",
  "scale.first": "人多的夜晚，一张票和一次收费必须仍然精确。",
  "scale.line": "用一条队列，并标明正在等待，这样人潮不会冲垮做决定的那一间。",
  "scale.cache": "公开的提示可以旧几秒钟，付款不可以。",
  "observe.check": "有人说失败了，就需要那一次请求走过的路径。",
  "observe.bench": "一次请求是追踪，有多少次是指标，写下的内容是日志。",
  "observe.night": "顺着那一次更新，从点按一直跟到记录，而不是重启然后指望好运。",
  "observe.alert": "警报要写出要做的动作和负责的角色，而不是只发出噪音。",
  "observe.quiet": "不要因为一张变慢的图片就呼叫一个人。",
  "security.check": "认证是你是谁，授权是你可以做什么。",
  "security.bench": "共用的密码、写在网址里的成绩，以及笔记本电脑上的备份，都是泄漏。",
  "security.who": "每个人有自己的登录，这样才能知道是谁做的。",
  "security.grades": "学生看自己的作业，老师看自己的班级，办公室看自己该做的工作。",
  "security.leak": "私人记录的备份锁给一个有名字的角色，不放在带回家的笔记本电脑上。",
  "futures.check": "工具可以换，对这个人的承诺不会过期。",
  "futures.bench": "工具可以更换，但不能接受一个走不掉的选择。",
  "futures.keep": "目录离开供应商也仍然能读，因为记录不属于供应商。",
  "futures.prepare": "在依赖那扇新门之前，先试好一条离开的路。",
  "futures.refuse": "不要把唯一的副本放进一个你无法离开的服务里。",
  "brief.tools": "Harbor Market 的工作人员用带历史的共享工作台，不用一台带回家的笔记本电脑。",
  "brief.platforms": "顾客、摊主和办公室是三扇门，背后是同一份摊位记录。",
  "brief.design": "先设计任务：今晚什么开着，以及谁可以说。",
  "brief.tiers": "这个人能不能改这个摊位，由应用程序决定，不只由浏览器决定。",
  "brief.integration": "红色的检查清单要挡住，市场用上一次绿色的版本开门。",
  "brief.deployment": "对公共告示板做一小步发布，并带一条排练过的退路。",
  "brief.maintain": "公开的文字和必须保持精确的内容分开，并留下地图。",
  "brief.scale": "拥挤的夜晚，一次改动的记录和任何付款都保持精确。",
  "brief.observe": "保存失败时，顺着那一次请求的路径看下去。",
  "brief.security": "摊主看自己的摊位，办公室的角色看它在那里要做的工作。",
  "brief.futures": "新的门只有在 Harbor Market 能够离开、并且仍然保住记录时才可以接受。",
};

const ja: Record<string, string> = {
  "tools.check": "変更履歴があれば、二人で同じ作業を直しても、片方がもう片方を消してしまいません。",
  "tools.bench": "仕事に名前をつけ、共有の作業台を開き、小さな変更を一つ行い、理由を添えて保存し、同僚に見せます。",
  "tools.where": "診療所の仕事は共有の作業台に置き、夜に家へ持ち帰る一台のノートパソコンには置きません。",
  "tools.memory": "履歴は保存された変更を覚えているので、一人の記憶に頼らなくて済みます。",
  "tools.fail": "検査に失敗したら止まり、その失敗した変更を、人が使う机の上には置きません。",
  "platforms.check": "画面はプラットフォームごとに変わってよいですが、記録とそのルールは同じままです。",
  "platforms.bench": "乗客は電話、検査係は手持ちの端末、夜の席はキーボード付きの画面を使い、どれも一つの記録を見ます。",
  "platforms.rider": "停留所のあいだにいる乗客には、事務所へ戻るのではなく、電話のページが必要です。",
  "platforms.same": "同じままなのは、一つの乗車券の記録とそのルールであり、画面の色ではありません。",
  "platforms.avoid": "すべての扉の後ろには一つの記録を置きます。三つのデータベースは食い違い始めます。",
  "design.check": "色やロゴやデータベースの形より先に、その人の仕事を設計します。",
  "design.bench": "質問は一度に一つにし、いつでも戻れる道を残します。",
  "design.first": "色やロゴからではなく、その人自身の言葉で表した仕事から始めます。",
  "design.error": "何が間違ったかと次の行動を伝え、すでに入力した答えは残します。",
  "design.access": "キーボードだけを使う人、初めての人や疲れている人も含めて、最後まで終えられるようにします。",
  "tiers.check": "その人が何をしてよいかという決定は、ルールが動くアプリケーションに置きます。",
  "tiers.bench": "ブラウザは見せ、アプリケーションは決め、データベースは覚えます。",
  "tiers.allowed": "この人が行動してよいかは、ほかのルールと一緒にアプリケーションが決めます。",
  "tiers.remember": "朝になっても残っていなければならないものは、データベースが覚えます。",
  "tiers.public": "決める部屋が止まっているときは、答えを作らず、掲示が使えないと伝えます。",
  "integration.check": "赤は先へ進まないという意味です。その変更は、まだ共有の仕事に加えてはいけません。",
  "integration.bench": "変更し、チェックリストを走らせ、二人目が見てから、初めて合流させます。",
  "integration.night": "赤い変更は止め、朝は最後に緑だった版で開きます。",
  "integration.who": "書いた人と二人目が両方見て、チェックリストが緑になってからにします。",
  "integration.secret": "秘密はログに入れません。チェックリストが緑でも同じです。",
  "deployment.check": "変更を人の前に出す前に、すでに分かっている戻る道が必要です。",
  "deployment.bench": "まず一つの病棟だけ変え、先へ進む前に戻り方をリハーサルします。",
  "deployment.size": "病院全体を一度にではなく、一つの病棟から始めます。",
  "deployment.back": "戻る道はリハーサル済みなので、夜勤の人が自分で始められます。",
  "deployment.tell": "何が変わり、どう戻るかを、分かりやすい言葉で看護師と調整役に伝えます。",
  "maintain.check": "新しい人が、残りを壊さずに一つの部分を変えられるようにします。",
  "maintain.bench": "礼状と支払いを分け、どれがどれかを書いた地図を残します。",
  "maintain.letter": "手紙は支払いと分けておき、言葉の変更がお金に触れないようにします。",
  "maintain.owner": "夜の電話は、名前のついた役割が受けます。群衆でも、誰もいないのでもありません。",
  "maintain.words": "地図は書き残し、次の人が記憶から組み直さなくて済むようにします。",
  "scale.check": "正確だと約束したことは正確なままにします。人に一度だけ請求する、というようなことです。",
  "scale.bench": "まず一枚の券と一回の請求を守ります。きれいなページは待てます。",
  "scale.first": "混んだ夜でも、一枚の券と一回の請求は正確なままです。",
  "scale.line": "待っている状態がはっきりした待ち行列を使い、人波が決める部屋を倒さないようにします。",
  "scale.cache": "公開のヒントは数秒古くてかまいません。支払いはだめです。",
  "observe.check": "失敗したと言われたときは、その一つの要求が通った道が必要です。",
  "observe.bench": "一つの要求はトレース、いくつあったかはメトリクス、書かれた内容はログです。",
  "observe.night": "再起動して運を待つのではなく、その一つの更新を、タップから記録まで追います。",
  "observe.alert": "警報は、する行動とそれを担う役割の名前を言い、ただ騒ぐだけにはしません。",
  "observe.quiet": "遅い絵が一枚だからといって、人を呼び出してはいけません。",
  "security.check": "認証はあなたが誰かであり、認可は何をしてよいかです。",
  "security.bench": "共有のパスワード、アドレスに入った成績、ノートパソコンのバックアップが、漏れです。",
  "security.who": "誰がしたか分かるように、一人ひとりが自分のログインを持ちます。",
  "security.grades": "生徒は自分の課題を見、教員は自分のクラスを見、事務は自分の仕事を見ます。",
  "security.leak": "個人の記録のバックアップは、名前のついた役割に鍵をかけ、家へ持ち帰るノートパソコンには置きません。",
  "futures.check": "道具は変わってよいですが、その人への約束は古くなりません。",
  "futures.bench": "道具は替えてよいです。離れられない選択は拒みます。",
  "futures.keep": "目録は業者なしでも読めるままにします。記録は業者のものではないからです。",
  "futures.prepare": "新しい扉に頼る前に、離れる道を試しておきます。",
  "futures.refuse": "離れられないサービスに、唯一のコピーを置いてはいけません。",
  "brief.tools": "Harbor Market の職員は、履歴のある共有の作業台で働き、家へ持ち帰る一台のノートパソコンでは働きません。",
  "brief.platforms": "買い物をする人、屋台の人、事務所は、一つの屋台の記録に向かう三つの扉です。",
  "brief.design": "先に仕事を設計します。今夜何が開いているか、そして誰がそう言ってよいかです。",
  "brief.tiers": "この人がこの屋台を直してよいかは、ブラウザだけでなく、アプリケーションが決めます。",
  "brief.integration": "赤いチェックリストは止め、市場は最後に緑だった版で開きます。",
  "brief.deployment": "公開の掲示への変更は小さく出し、リハーサルした戻る道を付けます。",
  "brief.maintain": "公開の言葉と、正確でなければならないものを分け、地図を残します。",
  "brief.scale": "混んだ夜でも、変更の記録と支払いは正確なままです。",
  "brief.observe": "保存に失敗したら、その一つの要求の道を追います。",
  "brief.security": "屋台の人は自分の屋台を見、事務所の役割は自分がいる理由である仕事を見ます。",
  "brief.futures": "新しい扉は、Harbor Market が離れても記録を残せるときだけ受け入れます。",
};

const ar: Record<string, string> = {
  "tools.check": "سجل الإصدارات يتيح لشخصين تغيير العمل نفسه من دون أن يمحو أحدهما الآخر.",
  "tools.bench": "سمّ العمل، وافتح منضدة العمل المشتركة، وأجر تغييرا صغيرا واحدا، واحفظه مع السبب، ثم أره لزميلك.",
  "tools.where": "عمل العيادة يبقى على منضدة عمل مشتركة، لا على حاسوب محمول يعود إلى البيت ليلا.",
  "tools.memory": "التاريخ يتذكر كل تغيير محفوظ، فلا يعتمد الفريق على ذاكرة شخص واحد.",
  "tools.fail": "إذا فشل الفحص، توقف، ولا تضع ذلك التغيير الفاشل على المكتب حيث سيستخدمه الناس.",
  "platforms.check": "قد تتغير الشاشة من منصة إلى أخرى، أما السجل وقواعده فيبقيان كما هما.",
  "platforms.bench": "الراكب يستخدم هاتفا، والمفتش جهازا يدويا، ومكتب الليل شاشة بلوحة مفاتيح، وكلهم على سجل واحد.",
  "platforms.rider": "الراكب بين المحطات يحتاج صفحة هاتف، لا عودة إلى المكتب.",
  "platforms.same": "ما يبقى كما هو هو سجل تصريح الركوب الواحد وقواعده، لا لون كل شاشة.",
  "platforms.avoid": "سجل واحد خلف كل الأبواب، لأن ثلاث قواعد بيانات ستبدأ بالاختلاف.",
  "design.check": "صمم مهمة الشخص أولا، قبل اللون أو الشعار أو شكل قاعدة البيانات.",
  "design.bench": "سؤال واحد في كل مرة، مع طريق واضح للرجوع.",
  "design.first": "ابدأ بالمهمة بكلمات الشخص نفسه، لا بلون أو شعار.",
  "design.error": "قل ما الذي أخطأ وما الفعل التالي، واحتفظ بالإجابات التي قدمها.",
  "design.access": "من يستخدم لوحة المفاتيح فقط، بمن في ذلك شخص جديد أو متعب، يجب أن يستطيع الإنهاء.",
  "tiers.check": "القرار عما يجوز للشخص فعله يعيش في التطبيق، حيث تعمل القواعد.",
  "tiers.bench": "المتصفح يعرض، والتطبيق يقرر، وقاعدة البيانات تتذكر.",
  "tiers.allowed": "جواز أن يتصرف هذا الشخص يُحسم في التطبيق، مع بقية القواعد.",
  "tiers.remember": "ما يجب أن يبقى موجودا في الصباح تتذكره قاعدة البيانات.",
  "tiers.public": "إذا توقفت الغرفة التي تقرر، قل إن اللوحة غير متاحة، ولا تخترع جوابا.",
  "integration.check": "الأحمر يعني لا تتابع: التغيير ليس جاهزا للانضمام إلى العمل المشترك.",
  "integration.bench": "أجر التغيير، ثم قائمة التحقق، ثم ينظر شخص ثان، وبعد ذلك فقط يُدمج.",
  "integration.night": "امنع التغيير الأحمر، فيستخدم الصباح آخر نسخة كانت خضراء.",
  "integration.who": "الكاتب وشخص ثان ينظران، وبعد أن تصبح قائمة التحقق خضراء فقط.",
  "integration.secret": "الأسرار لا تنتمي إلى سجل القائمة، حتى لو كانت القائمة خضراء.",
  "deployment.check": "النشر يحتاج طريقا للرجوع، معروفا مسبقا، قبل أن يصل التغيير إلى الناس.",
  "deployment.bench": "غيّر جناحا واحدا أولا، وجرّب الرجوع قبل أن تتقدم أكثر.",
  "deployment.size": "ابدأ بجناح واحد، لا بالمستشفى كله دفعة واحدة.",
  "deployment.back": "طريق الرجوع مجرّب، حتى يستطيع شخص في نوبة الليل أن يبدأه.",
  "deployment.tell": "أخبر الممرضين والمنسق بكلام واضح: ما الذي تغيّر، وكيف يرجعون.",
  "maintain.check": "يستطيع شخص جديد تغيير قطعة واحدة من دون أن يكسر الباقي.",
  "maintain.bench": "افصل رسالة الشكر عن الدفع، واترك خريطة مكتوبة تبين أي قطعة هي.",
  "maintain.letter": "تبقى الرسالة بمعزل عن الدفع، حتى لا يمس تغيير الكلمات المال.",
  "maintain.owner": "يتلقى اتصال الليل دور له اسم: لا حشد، ولا يُترك بلا أحد.",
  "maintain.words": "الخريطة مكتوبة، حتى لا يعيد الشخص التالي بناءها من الذاكرة.",
  "scale.check": "ما وُعد به بدقة يبقى دقيقا، مثل أن يُحصّل من الشخص مرة واحدة.",
  "scale.bench": "احم تذكرة واحدة وتحصيلا واحدا أولا؛ الصفحة الأجمل يمكنها الانتظار.",
  "scale.first": "في ليلة مزدحمة، يجب أن تبقى تذكرة واحدة وتحصيل واحد دقيقين.",
  "scale.line": "استخدم طابورا بحالة انتظار واضحة، حتى لا يوقع الزحام الغرفة التي تقرر.",
  "scale.cache": "تلميح عام قد يتأخر بضع ثوان، أما الدفع فلا.",
  "observe.check": "حين يقول أحد إن الأمر فشل، يلزم مسار ذلك الطلب الواحد.",
  "observe.bench": "الطلب الواحد أثر، والعدد مقياس، وما كُتب سجل.",
  "observe.night": "اتبع ذلك التحديث الواحد من اللمسة إلى السجل، بدلا من إعادة التشغيل ثم الأمل.",
  "observe.alert": "التنبيه يسمّي الفعل والدور الذي يقوم به، ولا يكتفي بإحداث ضجيج.",
  "observe.quiet": "لا تستدع شخصا من أجل صورة واحدة بطيئة.",
  "security.check": "المصادقة هي من أنت، والتفويض هو ما يجوز لك أن تفعل.",
  "security.bench": "كلمة مرور مشتركة، ودرجات في عنوان الصفحة، ونسخة احتياطية على حاسوب محمول: هذه هي التسريبات.",
  "security.who": "لكل شخص دخول خاص به، حتى يُعرف من فعل.",
  "security.grades": "الطالب يرى عمله، والمعلم يرى صفه، والمكتب يرى العمل المطلوب منه.",
  "security.leak": "تبقى النسخة الاحتياطية للسجلات الخاصة مقفلة لدور مسمّى، لا على حاسوب محمول يعود إلى البيت.",
  "futures.check": "الأدوات قد تتغير، أما الوعد للشخص فلا ينتهي أجله.",
  "futures.bench": "يجوز تغيير الأدوات، ويُرفض اختيار لا يمكن مغادرته.",
  "futures.keep": "يبقى الفهرس مقروءا من دون المورّد، لأن السجل ليس ملكه.",
  "futures.prepare": "جرّب طريقا للمغادرة قبل أن تعتمد على الباب الجديد.",
  "futures.refuse": "لا تضع النسخة الوحيدة في خدمة لا تستطيع مغادرتها.",
  "brief.tools": "يعمل موظفو Harbor Market على منضدة مشتركة لها تاريخ، لا على حاسوب محمول يعود إلى البيت.",
  "brief.platforms": "المتسوق وصاحب الكشك والمكتب ثلاثة أبواب على سجل كشك واحد.",
  "brief.design": "صمم المهمة أولا: ما المفتوح الليلة، ومن يجوز له أن يقول ذلك.",
  "brief.tiers": "قرار تعديل هذا الكشك يُحسم في التطبيق، لا في المتصفح وحده.",
  "brief.integration": "قائمة التحقق الحمراء تُمنع، ويفتح السوق على آخر نسخة خضراء.",
  "brief.deployment": "انشر تغييرا صغيرا على اللوحة العامة، مع طريق رجوع مجرّب.",
  "brief.maintain": "تبقى الكلمات العامة بمعزل عما يجب أن يبقى دقيقا، مع خريطة.",
  "brief.scale": "في ليلة مزدحمة يبقى سجل التغيير دقيقا، وكذلك أي دفع.",
  "brief.observe": "إذا فشل الحفظ، اتبع مسار ذلك الطلب الواحد.",
  "brief.security": "صاحب الكشك يرى كشكه، ودور المكتب يرى العمل الذي وُجد من أجله.",
  "brief.futures": "الباب الجديد مقبول فقط إذا استطاع Harbor Market مغادرته مع الإبقاء على السجل.",
};

const lines: Record<Locale, Record<string, string>> = { en, es, fr, de, pt, zh, ja, ar };

export function explain(locale: Locale, id: string): string {
  return lines[locale]?.[id] ?? lines.en[id] ?? "";
}
