import { randomBytes } from "node:crypto";
import { mkdirSync, writeFileSync, readFileSync, unlinkSync } from "node:fs";
import path from "node:path";
import { dataDir } from "./db";
import { ensureRecords } from "./db";
import { extractText, fileHash, reviewDocument, type ReviewResult } from "./review";
import { sqlAll, sqlExec, sqlGet, sqlRun, usesPostgres } from "./sql";
import { weeks, type WorkWindow } from "./term";

export type AttemptRow = { userId: string; itemId: string; kind: string; correct: boolean; createdAt: number };

export type ClassFile = {
  id: string;
  weekId: string;
  userId: string;
  name: string;
  mime: string;
  bytes: number;
  scope: "class" | "own";
  createdAt: number;
};

const allowed = new Set([
  "application/pdf",
  "text/plain",
  "text/markdown",
  "text/csv",
  "image/png",
  "image/jpeg",
  "image/svg+xml",
  "application/json",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
]);

let book: Promise<void> | null = null;

export function ensureClassbook(): Promise<void> {
  if (!book) {
    book = openBook().catch((error: unknown) => {
      book = null;
      throw error;
    });
  }
  return book;
}

async function openBook(): Promise<void> {
  await ensureRecords();
  await sqlExec(usesPostgres() ? postgresBook : sqliteBook);
  const own = await sqlAll<{ id: string }>(`SELECT id FROM keel_file WHERE scope = 'own'`);
  for (const row of own) {
    await sqlRun(`DELETE FROM keel_file WHERE id = ?`, [row.id]);
    try {
      unlinkSync(path.join(uploadsDir(), row.id));
    } catch {
      /* already gone */
    }
  }
  const count = await sqlGet<{ count: number }>(`SELECT COUNT(*) AS count FROM keel_week_work`);
  if (Number(count?.count ?? 0) === 0) {
    for (const week of weeks) {
      await sqlRun(
        `INSERT INTO keel_week_work (id, week_no, title, brief, status, opens_at, closes_at, updated_at, updated_by)
         VALUES (?, ?, ?, ?, 'published', NULL, NULL, ?, NULL)`,
        [week.id, week.no, week.title, week.promise, Date.now()],
      );
    }
  }
}

const sqliteBook = `
    CREATE TABLE IF NOT EXISTS keel_attempt (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id TEXT NOT NULL,
      item_id TEXT NOT NULL,
      kind TEXT NOT NULL,
      correct INTEGER NOT NULL,
      created_at INTEGER NOT NULL
    );
    CREATE INDEX IF NOT EXISTS keel_attempt_user ON keel_attempt(user_id, created_at);
    CREATE TABLE IF NOT EXISTS keel_week_work (
      id TEXT PRIMARY KEY,
      week_no INTEGER NOT NULL,
      title TEXT NOT NULL,
      brief TEXT NOT NULL,
      status TEXT NOT NULL,
      opens_at INTEGER,
      closes_at INTEGER,
      updated_at INTEGER NOT NULL,
      updated_by TEXT
    );
    CREATE TABLE IF NOT EXISTS keel_file (
      id TEXT PRIMARY KEY,
      week_id TEXT NOT NULL,
      user_id TEXT NOT NULL,
      name TEXT NOT NULL,
      mime TEXT NOT NULL,
      bytes INTEGER NOT NULL,
      scope TEXT NOT NULL,
      created_at INTEGER NOT NULL
    );
    CREATE TABLE IF NOT EXISTS keel_rating (
      user_id TEXT NOT NULL,
      week_id TEXT NOT NULL,
      stars INTEGER NOT NULL,
      note TEXT,
      created_at INTEGER NOT NULL,
      PRIMARY KEY (user_id, week_id)
    );
    CREATE TABLE IF NOT EXISTS keel_survey (
      user_id TEXT PRIMARY KEY,
      helped INTEGER NOT NULL,
      why TEXT NOT NULL,
      better TEXT NOT NULL,
      ease INTEGER NOT NULL,
      recommend INTEGER NOT NULL,
      created_at INTEGER NOT NULL
    );
    CREATE TABLE IF NOT EXISTS keel_invite (
      code TEXT PRIMARY KEY,
      from_user TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      used_by TEXT
    );
    CREATE TABLE IF NOT EXISTS keel_review (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      week_id TEXT NOT NULL,
      sha256 TEXT NOT NULL,
      bytes INTEGER NOT NULL,
      assessment INTEGER NOT NULL,
      coverage INTEGER NOT NULL,
      plagiarism INTEGER NOT NULL,
      similarity INTEGER NOT NULL,
      match_kind TEXT NOT NULL,
      created_at INTEGER NOT NULL
    );
    CREATE TABLE IF NOT EXISTS keel_fingerprint (
      review_id TEXT NOT NULL,
      shingle TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS keel_fingerprint_shingle ON keel_fingerprint(shingle);
    CREATE TABLE IF NOT EXISTS keel_course (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      summary TEXT NOT NULL,
      status TEXT NOT NULL,
      opens_at INTEGER,
      closes_at INTEGER,
      updated_at INTEGER NOT NULL,
      updated_by TEXT
    );
    CREATE TABLE IF NOT EXISTS keel_announcement (
      id TEXT PRIMARY KEY,
      course_id TEXT,
      title TEXT NOT NULL,
      body TEXT NOT NULL,
      status TEXT NOT NULL,
      publish_at INTEGER,
      updated_at INTEGER NOT NULL,
      updated_by TEXT
    );
`;

const postgresBook = `
    CREATE TABLE IF NOT EXISTS keel_attempt (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id TEXT NOT NULL,
      item_id TEXT NOT NULL,
      kind TEXT NOT NULL,
      correct INTEGER NOT NULL,
      created_at BIGINT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS keel_attempt_user ON keel_attempt(user_id, created_at);
    CREATE TABLE IF NOT EXISTS keel_week_work (
      id TEXT PRIMARY KEY,
      week_no INTEGER NOT NULL,
      title TEXT NOT NULL,
      brief TEXT NOT NULL,
      status TEXT NOT NULL,
      opens_at BIGINT,
      closes_at BIGINT,
      updated_at BIGINT NOT NULL,
      updated_by TEXT
    );
    CREATE TABLE IF NOT EXISTS keel_file (
      id TEXT PRIMARY KEY,
      week_id TEXT NOT NULL,
      user_id TEXT NOT NULL,
      name TEXT NOT NULL,
      mime TEXT NOT NULL,
      bytes INTEGER NOT NULL,
      scope TEXT NOT NULL,
      created_at BIGINT NOT NULL,
      body BYTEA
    );
    CREATE TABLE IF NOT EXISTS keel_rating (
      user_id TEXT NOT NULL,
      week_id TEXT NOT NULL,
      stars INTEGER NOT NULL,
      note TEXT,
      created_at BIGINT NOT NULL,
      PRIMARY KEY (user_id, week_id)
    );
    CREATE TABLE IF NOT EXISTS keel_survey (
      user_id TEXT PRIMARY KEY,
      helped INTEGER NOT NULL,
      why TEXT NOT NULL,
      better TEXT NOT NULL,
      ease INTEGER NOT NULL,
      recommend INTEGER NOT NULL,
      created_at BIGINT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS keel_invite (
      code TEXT PRIMARY KEY,
      from_user TEXT NOT NULL,
      created_at BIGINT NOT NULL,
      used_by TEXT
    );
    CREATE TABLE IF NOT EXISTS keel_review (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL,
      week_id TEXT NOT NULL,
      sha256 TEXT NOT NULL,
      bytes INTEGER NOT NULL,
      assessment INTEGER NOT NULL,
      coverage INTEGER NOT NULL,
      plagiarism INTEGER NOT NULL,
      similarity INTEGER NOT NULL,
      match_kind TEXT NOT NULL,
      created_at BIGINT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS keel_fingerprint (
      review_id TEXT NOT NULL,
      shingle TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS keel_fingerprint_shingle ON keel_fingerprint(shingle);
    CREATE TABLE IF NOT EXISTS keel_course (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      summary TEXT NOT NULL,
      status TEXT NOT NULL,
      opens_at BIGINT,
      closes_at BIGINT,
      updated_at BIGINT NOT NULL,
      updated_by TEXT
    );
    CREATE TABLE IF NOT EXISTS keel_announcement (
      id TEXT PRIMARY KEY,
      course_id TEXT,
      title TEXT NOT NULL,
      body TEXT NOT NULL,
      status TEXT NOT NULL,
      publish_at BIGINT,
      updated_at BIGINT NOT NULL,
      updated_by TEXT
    );
`;

export async function recordAttempt(input: { userId: string; itemId: string; kind: string; correct: boolean }) {
  await ensureClassbook();
  await sqlRun(`INSERT INTO keel_attempt (user_id, item_id, kind, correct, created_at) VALUES (?, ?, ?, ?, ?)`, [
    input.userId,
    input.itemId,
    input.kind,
    input.correct ? 1 : 0,
    Date.now(),
  ]);
}

export async function attemptTotals(): Promise<{ userId: string; name: string; correct: number; attempts: number }[]> {
  await ensureClassbook();
  const rows = await sqlAll<{ user_id: string; name: string; correct: number; attempts: number }>(
    `SELECT p.user_id AS user_id, p.display_name AS name,
       SUM(CASE WHEN a.correct = 1 THEN 1 ELSE 0 END) AS correct,
       COUNT(a.id) AS attempts
     FROM keel_profile p
     JOIN keel_attempt a ON a.user_id = p.user_id
     GROUP BY p.user_id, p.display_name`,
  );
  return rows.map((row) => ({ userId: row.user_id, name: row.name, correct: Number(row.correct), attempts: Number(row.attempts) }));
}

export async function listAttempts(userId?: string): Promise<AttemptRow[]> {
  await ensureClassbook();
  const rows = userId
    ? await sqlAll<{ user_id: string; item_id: string; kind: string; correct: number; created_at: number }>(
        `SELECT user_id, item_id, kind, correct, created_at FROM keel_attempt WHERE user_id = ? ORDER BY created_at DESC`,
        [userId],
      )
    : await sqlAll<{ user_id: string; item_id: string; kind: string; correct: number; created_at: number }>(
        `SELECT user_id, item_id, kind, correct, created_at FROM keel_attempt ORDER BY created_at DESC LIMIT 400`,
      );
  return rows.map((row) => ({
    userId: row.user_id,
    itemId: row.item_id,
    kind: row.kind,
    correct: row.correct === 1,
    createdAt: row.created_at,
  }));
}

export async function cohort() {
  await ensureClassbook();
  const people = await sqlAll<{ id: string; email: string; name: string; display_name: string | null; role: string }>(
    `SELECT u.id AS id, u.email AS email, u.name AS name, p.display_name AS display_name, coalesce(p.role, 'student') AS role
     FROM "user" u
     LEFT JOIN keel_profile p ON p.user_id = u.id
     ORDER BY coalesce(p.display_name, u.name)`,
  );
  const totals = new Map((await attemptTotals()).map((row) => [row.userId, row]));
  return people.map((person) => {
    const tally = totals.get(person.id);
    return {
      id: person.id,
      email: person.email,
      name: person.display_name || person.name,
      role: person.role,
      correct: tally?.correct ?? 0,
      attempts: tally?.attempts ?? 0,
      failures: (tally?.attempts ?? 0) - (tally?.correct ?? 0),
    };
  });
}

export type WeekWork = WorkWindow & { id: string; weekNo: number; title: string; brief: string };

export async function listWork(): Promise<WeekWork[]> {
  await ensureClassbook();
  const rows = await sqlAll<{
    id: string;
    week_no: number;
    title: string;
    brief: string;
    status: WorkWindow["status"];
    opens_at: number | null;
    closes_at: number | null;
  }>(`SELECT id, week_no, title, brief, status, opens_at, closes_at FROM keel_week_work ORDER BY week_no`);
  return rows.map((row) => ({
    id: row.id,
    weekNo: row.week_no,
    title: row.title,
    brief: row.brief,
    status: row.status,
    opensAt: row.opens_at,
    closesAt: row.closes_at,
  }));
}

export async function workFor(weekId: string): Promise<WeekWork | null> {
  return (await listWork()).find((work) => work.id === weekId) ?? null;
}

export async function saveWork(input: {
  id: string;
  title: string;
  brief: string;
  status: WorkWindow["status"];
  opensAt: number | null;
  closesAt: number | null;
  userId: string;
}) {
  await ensureClassbook();
  const week = weeks.find((item) => item.id === input.id);
  if (!week) return false;
  await sqlRun(
    `INSERT INTO keel_week_work (id, week_no, title, brief, status, opens_at, closes_at, updated_at, updated_by)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(id) DO UPDATE SET
       title = excluded.title,
       brief = excluded.brief,
       status = excluded.status,
       opens_at = excluded.opens_at,
       closes_at = excluded.closes_at,
       updated_at = excluded.updated_at,
       updated_by = excluded.updated_by`,
    [input.id, week.no, input.title.slice(0, 120), input.brief.slice(0, 2000), input.status, input.opensAt, input.closesAt, Date.now(), input.userId],
  );
  return true;
}

export async function restoreWork(id: string) {
  const week = weeks.find((item) => item.id === id);
  if (!week) return false;
  await ensureClassbook();
  await sqlRun(
    `UPDATE keel_week_work SET title = ?, brief = ?, status = 'published', opens_at = NULL, closes_at = NULL, updated_at = ? WHERE id = ?`,
    [week.title, week.promise, Date.now(), id],
  );
  return true;
}

function uploadsDir() {
  const dir = path.join(dataDir, "uploads");
  mkdirSync(dir, { recursive: true });
  return dir;
}

type FileRow = {
  id: string;
  week_id: string;
  user_id: string;
  name: string;
  mime: string;
  bytes: number;
  scope: "class" | "own";
  created_at: number;
};

function asFile(row: FileRow): ClassFile {
  return {
    id: row.id,
    weekId: row.week_id,
    userId: row.user_id,
    name: row.name,
    mime: row.mime,
    bytes: row.bytes,
    scope: row.scope,
    createdAt: row.created_at,
  };
}

export async function saveUpload(input: { weekId: string; userId: string; name: string; mime: string; bytes: Buffer; scope: "class" | "own" }): Promise<ClassFile | null> {
  if (!weeks.some((week) => week.id === input.weekId) && !(await courseById(input.weekId))) return null;
  if (!allowed.has(input.mime)) return null;
  if (input.bytes.length < 1 || input.bytes.length > 4_000_000) return null;
  const clean = input.name.replace(/[^\w.\- ()]/g, "").slice(0, 80);
  if (!clean) return null;
  await ensureClassbook();
  const id = randomBytes(12).toString("hex");
  const createdAt = Date.now();
  if (usesPostgres()) {
    await sqlRun(
      `INSERT INTO keel_file (id, week_id, user_id, name, mime, bytes, scope, created_at, body) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [id, input.weekId, input.userId, clean, input.mime, input.bytes.length, input.scope, createdAt, input.bytes],
    );
  } else {
    writeFileSync(path.join(uploadsDir(), id), input.bytes);
    await sqlRun(`INSERT INTO keel_file (id, week_id, user_id, name, mime, bytes, scope, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`, [
      id,
      input.weekId,
      input.userId,
      clean,
      input.mime,
      input.bytes.length,
      input.scope,
      createdAt,
    ]);
  }
  return { id, weekId: input.weekId, userId: input.userId, name: clean, mime: input.mime, bytes: input.bytes.length, scope: input.scope, createdAt };
}

export async function filesFor(weekId: string, userId: string, staff: boolean): Promise<ClassFile[]> {
  await ensureClassbook();
  const rows = await sqlAll<FileRow>(
    `SELECT id, week_id, user_id, name, mime, bytes, scope, created_at FROM keel_file WHERE week_id = ? ORDER BY created_at DESC`,
    [weekId],
  );
  return rows.filter((row) => staff || row.scope === "class" || row.user_id === userId).map(asFile);
}

export async function readUpload(id: string, userId: string, staff: boolean): Promise<{ file: ClassFile; bytes: Buffer } | null> {
  await ensureClassbook();
  if (!/^[a-f0-9]{24}$/.test(id)) return null;
  const row = await sqlGet<FileRow & { body?: Buffer | null }>(
    usesPostgres()
      ? `SELECT id, week_id, user_id, name, mime, bytes, scope, created_at, body FROM keel_file WHERE id = ?`
      : `SELECT id, week_id, user_id, name, mime, bytes, scope, created_at FROM keel_file WHERE id = ?`,
    [id],
  );
  if (!row) return null;
  if (!staff && row.scope !== "class" && row.user_id !== userId) return null;
  if (usesPostgres()) {
    const body = row.body;
    if (!body) return null;
    return { file: asFile(row), bytes: Buffer.isBuffer(body) ? body : Buffer.from(body) };
  }
  const stored = path.join(uploadsDir(), id);
  if (!stored.startsWith(uploadsDir())) return null;
  return { file: asFile(row), bytes: readFileSync(stored) };
}

export async function deleteUpload(id: string, userId: string, staff: boolean): Promise<boolean> {
  await ensureClassbook();
  const row = await sqlGet<{ user_id: string }>(`SELECT user_id FROM keel_file WHERE id = ?`, [id]);
  if (!row) return false;
  if (!staff && row.user_id !== userId) return false;
  await sqlRun(`DELETE FROM keel_file WHERE id = ?`, [id]);
  try {
    unlinkSync(path.join(uploadsDir(), id));
  } catch {
    /* already gone */
  }
  return true;
}

export async function rateWeek(userId: string, weekId: string, stars: number, note: string) {
  if (!weeks.some((week) => week.id === weekId)) return false;
  if (stars < 1 || stars > 5) return false;
  await ensureClassbook();
  await sqlRun(
    `INSERT INTO keel_rating (user_id, week_id, stars, note, created_at) VALUES (?, ?, ?, ?, ?)
     ON CONFLICT(user_id, week_id) DO UPDATE SET stars = excluded.stars, note = excluded.note, created_at = excluded.created_at`,
    [userId, weekId, stars, note.slice(0, 500), Date.now()],
  );
  return true;
}

export async function ratings(): Promise<{ weekId: string; stars: number; count: number }[]> {
  await ensureClassbook();
  const rows = await sqlAll<{ week_id: string; stars: number; count: number }>(
    `SELECT week_id, AVG(stars) AS stars, COUNT(*) AS count FROM keel_rating GROUP BY week_id`,
  );
  return rows.map((row) => ({ weekId: row.week_id, stars: Number(row.stars), count: Number(row.count) }));
}

export async function saveSurvey(input: { userId: string; helped: boolean; why: string; better: string; ease: number; recommend: boolean }) {
  if (input.why.trim().length < 20 || input.better.trim().length < 20) return false;
  if (input.ease < 1 || input.ease > 5) return false;
  await ensureClassbook();
  await sqlRun(
    `INSERT INTO keel_survey (user_id, helped, why, better, ease, recommend, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(user_id) DO UPDATE SET helped = excluded.helped, why = excluded.why, better = excluded.better, ease = excluded.ease, recommend = excluded.recommend, created_at = excluded.created_at`,
    [input.userId, input.helped ? 1 : 0, input.why.trim().slice(0, 2000), input.better.trim().slice(0, 2000), input.ease, input.recommend ? 1 : 0, Date.now()],
  );
  return true;
}

export async function surveyFor(userId: string) {
  await ensureClassbook();
  const row = await sqlGet<{ helped: number; why: string; better: string; ease: number; recommend: number }>(
    `SELECT helped, why, better, ease, recommend FROM keel_survey WHERE user_id = ?`,
    [userId],
  );
  if (!row) return null;
  return { helped: row.helped === 1, why: row.why, better: row.better, ease: row.ease, recommend: row.recommend === 1 };
}

export type HeldReview = {
  id: string;
  weekId: string;
  userId: string;
  name: string;
  sha256: string;
  assessment: boolean;
  coverage: number;
  plagiarism: boolean;
  similarity: number;
  match: ReviewResult["match"];
  createdAt: number;
};

export async function reviewAndDiscard(input: { weekId: string; userId: string; name: string; mime: string; bytes: Buffer }): Promise<HeldReview | null> {
  const week = weeks.find((item) => item.id === input.weekId);
  if (!week) return null;
  if (input.bytes.length < 1 || input.bytes.length > 4_000_000) return null;
  await ensureClassbook();
  const work = await workFor(input.weekId);
  const text = extractText(input.bytes, input.mime, input.name);
  const sha256 = fileHash(input.bytes);
  const peers = await peerPrints(input.weekId, input.userId);
  const reviewed = reviewDocument({ text, weekBrief: `${week.title} ${week.promise} ${work?.brief ?? ""}`, sha256, peers });
  const id = randomBytes(12).toString("hex");
  const createdAt = Date.now();
  await sqlRun(
    `INSERT INTO keel_review (id, user_id, week_id, sha256, bytes, assessment, coverage, plagiarism, similarity, match_kind, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      id,
      input.userId,
      input.weekId,
      reviewed.sha256,
      input.bytes.length,
      reviewed.assessment ? 1 : 0,
      reviewed.coverage,
      reviewed.plagiarism ? 1 : 0,
      reviewed.similarity,
      reviewed.match,
      createdAt,
    ],
  );
  for (const shingle of reviewed.shingles) await sqlRun(`INSERT INTO keel_fingerprint (review_id, shingle) VALUES (?, ?)`, [id, shingle]);
  return {
    id,
    weekId: input.weekId,
    userId: input.userId,
    name: input.userId,
    sha256: reviewed.sha256,
    assessment: reviewed.assessment,
    coverage: reviewed.coverage,
    plagiarism: reviewed.plagiarism,
    similarity: reviewed.similarity,
    match: reviewed.match,
    createdAt,
  };
}

async function peerPrints(weekId: string, userId: string): Promise<{ sha256: string; shingles: string[] }[]> {
  const reviews = await sqlAll<{ id: string; sha256: string }>(`SELECT id, sha256 FROM keel_review WHERE week_id = ? AND user_id != ?`, [weekId, userId]);
  const prints: { sha256: string; shingles: string[] }[] = [];
  for (const review of reviews) {
    const rows = await sqlAll<{ shingle: string }>(`SELECT shingle FROM keel_fingerprint WHERE review_id = ?`, [review.id]);
    prints.push({ sha256: review.sha256, shingles: rows.map((row) => row.shingle) });
  }
  return prints;
}

export async function reviewsFor(weekId: string, userId: string, staff: boolean): Promise<HeldReview[]> {
  await ensureClassbook();
  const rows = await sqlAll<{
    id: string;
    user_id: string;
    week_id: string;
    sha256: string;
    assessment: number;
    coverage: number;
    plagiarism: number;
    similarity: number;
    match_kind: ReviewResult["match"];
    created_at: number;
  }>(
    `SELECT id, user_id, week_id, sha256, assessment, coverage, plagiarism, similarity, match_kind, created_at
     FROM keel_review WHERE week_id = ? ORDER BY created_at DESC`,
    [weekId],
  );
  return rows
    .filter((row) => staff || row.user_id === userId)
    .map((row) => ({
      id: row.id,
      weekId: row.week_id,
      userId: staff ? row.user_id : "",
      name: staff ? row.user_id : "",
      sha256: row.sha256.slice(0, 12),
      assessment: row.assessment === 1,
      coverage: row.coverage,
      plagiarism: row.plagiarism === 1,
      similarity: row.similarity,
      match: row.match_kind,
      createdAt: row.created_at,
    }));
}

export async function allReviews(): Promise<HeldReview[]> {
  await ensureClassbook();
  const rows = await sqlAll<{
    id: string;
    user_id: string;
    week_id: string;
    sha256: string;
    assessment: number;
    coverage: number;
    plagiarism: number;
    similarity: number;
    match_kind: ReviewResult["match"];
    created_at: number;
    name: string;
  }>(
    `SELECT r.id, r.user_id, r.week_id, r.sha256, r.assessment, r.coverage, r.plagiarism, r.similarity, r.match_kind, r.created_at,
            coalesce(p.display_name, 'Learner') AS name
     FROM keel_review r
     LEFT JOIN keel_profile p ON p.user_id = r.user_id
     ORDER BY r.created_at DESC LIMIT 80`,
  );
  return rows.map((row) => ({
    id: row.id,
    weekId: row.week_id,
    userId: row.user_id,
    name: row.name,
    sha256: row.sha256.slice(0, 12),
    assessment: row.assessment === 1,
    coverage: row.coverage,
    plagiarism: row.plagiarism === 1,
    similarity: row.similarity,
    match: row.match_kind,
    createdAt: row.created_at,
  }));
}

export type CourseRow = WorkWindow & { id: string; title: string; summary: string };
export type AnnouncementRow = { id: string; courseId: string; title: string; body: string; status: WorkWindow["status"]; publishAt: number | null };

export async function listCourses(): Promise<CourseRow[]> {
  await ensureClassbook();
  const rows = await sqlAll<{ id: string; title: string; summary: string; status: WorkWindow["status"]; opens_at: number | null; closes_at: number | null }>(
    `SELECT id, title, summary, status, opens_at, closes_at FROM keel_course ORDER BY updated_at DESC`,
  );
  return rows.map((row) => ({ id: row.id, title: row.title, summary: row.summary, status: row.status, opensAt: row.opens_at, closesAt: row.closes_at }));
}

export async function courseById(id: string): Promise<CourseRow | null> {
  return (await listCourses()).find((course) => course.id === id) ?? null;
}

export async function saveCourse(input: { id?: string; title: string; summary: string; status: WorkWindow["status"]; opensAt: number | null; closesAt: number | null; userId: string }): Promise<string | null> {
  const title = input.title.trim().slice(0, 120);
  const summary = input.summary.trim().slice(0, 2000);
  if (title.length < 2 || summary.length < 2) return null;
  await ensureClassbook();
  const id = input.id && (await courseById(input.id)) ? input.id : `c${randomBytes(6).toString("hex")}`;
  await sqlRun(
    `INSERT INTO keel_course (id, title, summary, status, opens_at, closes_at, updated_at, updated_by)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(id) DO UPDATE SET title = excluded.title, summary = excluded.summary, status = excluded.status, opens_at = excluded.opens_at, closes_at = excluded.closes_at, updated_at = excluded.updated_at, updated_by = excluded.updated_by`,
    [id, title, summary, input.status, input.opensAt, input.closesAt, Date.now(), input.userId],
  );
  return id;
}

export async function deleteCourse(id: string): Promise<boolean> {
  if (!(await courseById(id))) return false;
  await ensureClassbook();
  await sqlRun(`DELETE FROM keel_course WHERE id = ?`, [id]);
  await sqlRun(`DELETE FROM keel_announcement WHERE course_id = ?`, [id]);
  return true;
}

export async function listAnnouncements(): Promise<AnnouncementRow[]> {
  await ensureClassbook();
  const rows = await sqlAll<{ id: string; course_id: string | null; title: string; body: string; status: WorkWindow["status"]; publish_at: number | null }>(
    `SELECT id, course_id, title, body, status, publish_at FROM keel_announcement ORDER BY coalesce(publish_at, updated_at) DESC`,
  );
  return rows.map((row) => ({ id: row.id, courseId: row.course_id ?? "", title: row.title, body: row.body, status: row.status, publishAt: row.publish_at }));
}

export async function saveAnnouncement(input: { id?: string; courseId: string; title: string; body: string; status: WorkWindow["status"]; publishAt: number | null; userId: string }): Promise<string | null> {
  const title = input.title.trim().slice(0, 140);
  const body = input.body.trim().slice(0, 2000);
  if (title.length < 2 || body.length < 2) return null;
  await ensureClassbook();
  const id = input.id && (await listAnnouncements()).some((item) => item.id === input.id) ? input.id : `a${randomBytes(6).toString("hex")}`;
  await sqlRun(
    `INSERT INTO keel_announcement (id, course_id, title, body, status, publish_at, updated_at, updated_by)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?)
     ON CONFLICT(id) DO UPDATE SET course_id = excluded.course_id, title = excluded.title, body = excluded.body, status = excluded.status, publish_at = excluded.publish_at, updated_at = excluded.updated_at, updated_by = excluded.updated_by`,
    [id, input.courseId || null, title, body, input.status, input.publishAt, Date.now(), input.userId],
  );
  return id;
}

export async function deleteAnnouncement(id: string): Promise<boolean> {
  await ensureClassbook();
  const row = await sqlGet(`SELECT id FROM keel_announcement WHERE id = ?`, [id]);
  if (!row) return false;
  await sqlRun(`DELETE FROM keel_announcement WHERE id = ?`, [id]);
  return true;
}

export async function createInvite(userId: string): Promise<string> {
  await ensureClassbook();
  const code = randomBytes(4).toString("hex");
  await sqlRun(`INSERT INTO keel_invite (code, from_user, created_at) VALUES (?, ?, ?)`, [code, userId, Date.now()]);
  return code;
}
