import type { Pack } from "./types";

export const es: Pack = {
  sections: {
    tools: {
      title: "El banco de trabajo",
      promise: "Saber para qué sirve cada herramienta y en qué entorno vive de verdad el trabajo.",
      objectives: [
        "Nombrar el editor, el navegador, la terminal y el historial.",
        "Distinguir un portátil personal de un entorno compartido.",
        "Hacer cuatro preguntas sencillas antes de fiarte de una herramienta nueva.",
      ],
      start: [
        "Una herramienta te ayuda a hacer un cambio y a ver qué ocurrió. El editor es donde se escribe el trabajo. El navegador es donde una persona lo prueba. La terminal es una ventana sencilla donde pides a la máquina que ejecute una comprobación. Cada ventana tiene un trabajo. Cuando esos trabajos están separados, el trabajo se comparte con más claridad.",
        "Un entorno es el lugar donde corren esas herramientas. Tu portátil es un entorno. El mostrador de una clínica es otro. Una máquina compartida en un centro de datos es un tercero. El trabajo puede moverse. La promesa a la persona que usa el sistema, no.",
      ],
      how: [
        "El historial recuerda cada cambio guardado, quién lo hizo y una frase sobre el porqué. Dos personas pueden trabajar sin borrarse. Una lista de paquetes anota las piezas externas exactas, para que la construcción de mañana coincida con la de hoy. Un registro permite mirar una acción en lugar de adivinar.",
        "Ante una herramienta nueva, ignora el color de la ventana y pregunta: ¿pueden usarla dos personas sin pisarse? ¿Funciona igual en una segunda máquina? ¿Se puede deshacer? ¿Un fallo se lee en palabras? Si la respuesta es no, es un boceto, no un banco de trabajo.",
      ],
      expert: [
        "Los equipos unifican el banco de trabajo. Una persona nueva debería abrir el proyecto y ejecutar las comprobaciones el primer día. Eso exige que la preparación esté escrita, que los secretos no vivan dentro del proyecto y que las comprobaciones no dependan de una pantalla privada.",
        "El fallo caro es un sistema que solo funciona en la máquina de quien se fue. La moda de los editores cambia. El trabajo no: repetir, recuperar el ayer y explicar un fallo.",
      ],
      example: [
        "Harbor Market guarda el tablón público y el libro de puestos en un proyecto compartido. Quien tiene un puesto no abre el editor. El personal sí. El proyecto vive en un entorno gestionado, no en un portátil que se va a casa.",
        "Si ese portátil fuera la única copia, un café derramado cerraría los registros del mercado. El historial, no la marca del editor, es lo que permite recuperar el martes.",
      ],
      narration:
        "Una herramienta ayuda a hacer un cambio y a ver qué ocurrió. El editor es donde se escribe. El navegador es donde una persona prueba. La terminal es donde pides a la máquina una comprobación. El historial recuerda cada cambio guardado, así que dos personas no pueden borrarse. Harbor Market guarda ese historial en un banco compartido, no en un portátil que se va a casa por la noche.",
      checkPrompt: "¿Qué permite que dos personas cambien el trabajo sin borrarse en silencio?",
      checkOptions: ["Un tema de colores más vivo", "Un historial de cada cambio guardado", "Un monitor más grande", "Un ratón más rápido"],
      benchTitle: "Ordena la mañana",
      benchPrompt: "Alguien nuevo va a cambiar el horario de apertura. Ordena los pasos en los que confiarías.",
      benchItems: [
        "Di el trabajo en una frase.",
        "Abre el banco compartido, no una copia privada.",
        "Haz un solo cambio pequeño.",
        "Guárdalo en el historial, con una frase sobre el porqué.",
        "Enséñaselo a un colega antes de que siga adelante.",
      ],
      benchSlots: [],
      caseOrg: "Clínica Riverside",
      caseFile: "RC-01",
      caseTitle: "El mostrador y el único portátil",
      caseSituation: [
        "La Clínica Riverside deja reservar una enfermera por teléfono o en el mostrador. El cambio de la cita vive en un portátil que solo la recepcionista sabe abrir. Cuando ella no está, el mostrador anota las horas en papel y las teclea después.",
        "La clínica no es una empresa de software. Quienes atienden el mostrador no son desarrolladores. Aun así necesitan un banco de trabajo que otra persona formada pueda abrir un lunes.",
      ],
      caseTask: "Elige dónde debe vivir este trabajo y qué ocurre cuando una comprobación falla.",
      caseSteps: [
        "Lee los dos entornos: un portátil privado, o un banco compartido de la clínica con historial.",
        "Imagina un lunes en que la recepcionista no está y un paciente necesita mover una hora.",
        "Responde las tres decisiones con palabras llanas.",
        "En la nota, di qué abre primero el mostrador y qué no debe ser nunca la única copia.",
      ],
      decisions: [
        { prompt: "¿Dónde debe vivir el trabajo de las citas?", options: ["En el portátil personal de la recepcionista", "En un banco compartido que cualquier persona formada pueda abrir", "Solo en papel"] },
        { prompt: "¿Qué recuerda los cambios?", options: ["Quien estuviera ese día en el mostrador", "Un historial de cada cambio guardado", "Nada, si la gente va con cuidado"] },
        { prompt: "Una comprobación falla antes de llegar al mostrador. ¿Qué haces?", options: ["Lo pones en el mostrador de todos modos", "Paras, y no lo pones en el mostrador", "Ocultas el fallo para que la mañana siga tranquila"] },
      ],
      noteLabel: "Tu nota para la dirección de la clínica",
      noteHint: "Escribe qué debe abrir el mostrador y qué no debe ser nunca la única copia.",
    },
    platforms: {
      title: "Plataformas",
      promise: "Ver qué cambia entre un teléfono, un escritorio y un quiosco, y qué debe seguir igual.",
      objectives: ["Decir qué es una plataforma en una frase.", "Separar la pantalla del registro.", "Comparar dos plataformas sin dejarte llevar por la moda."],
      start: [
        "Una plataforma es el lugar donde una persona se encuentra con el sistema: un teléfono, un ordenador de escritorio, un quiosco, una tableta en un pasillo. La pantalla cambia. El trabajo, a menudo, no. Quien viaja quiere saber si el autobús llega. Quien inspecciona quiere saber si un pase vale. El turno de noche quiere la misma verdad, en una pantalla mayor, con teclado.",
        "Quienes no desarrollan también tienen que terminar una tarea. Si la plataforma la hace más difícil, la plataforma está mal, aunque parezca nueva.",
      ],
      how: [
        "Suele quedarse igual: quién es la persona, qué puede hacer, el registro de lo ocurrido y la promesa de que ese registro es verdadero. Suele cambiar: el tamaño de la pantalla, si hay teclado, si la red se cae y cuánta prisa tiene la persona.",
        "Una comparación útil es una tabla de tres filas. La tarea. Lo que debe ser verdad. Lo que la plataforma facilita o dificulta. Si dos plataformas no pueden compartir un registro, no tienes dos puertas. Tienes dos sistemas que van a contradecirse.",
      ],
      expert: [
        "El problema llega cuando cada plataforma crece con su propia copia de las reglas. El teléfono dice que el pase vale. El aparato de inspección dice que no. El turno de noche no sabe a cuál creer. La salida es un registro y un lugar donde se decide, con puertas finas delante.",
        "La falta de red importa. Un quiosco en una estación puede quedarse sin conexión. Decide antes de construir qué acciones esperan y cuáles se guardan para enviarlas después. Escríbelo. Forma parte de la elección de plataforma, no es una sorpresa.",
      ],
      example: [
        "Harbor Market tiene tres puertas hacia un solo libro de puestos. Quien compra usa una página de teléfono para ver qué está abierto. Quien tiene un puesto usa otra página sencilla para marcar abierto o cerrado. La oficina usa una pantalla de escritorio para el día completo.",
        "Las páginas se ven distintas. El registro es el mismo puesto, el mismo horario, la misma persona autorizada a cambiarlo. Una segunda hoja de cálculo privada haría mentir al tablón.",
      ],
      narration:
        "Una plataforma es donde una persona se encuentra con el sistema. La pantalla puede cambiar. El registro no debería. En Harbor Market quien compra, quien tiene un puesto y la oficina tienen cada uno una puerta distinta. Todos leen y escriben un solo libro. Si cada puerta guardara su copia, el tablón mentiría.",
      checkPrompt: "¿Qué debe permanecer igual al pasar un trabajo del teléfono al escritorio?",
      checkOptions: ["El color de los botones", "El registro y las reglas", "Las animaciones", "El lema"],
      benchTitle: "Tres trabajos, tres puertas",
      benchPrompt: "City Hopper gestiona un pase de transporte. Une cada trabajo con la puerta que le va. El registro del pase sigue siendo uno.",
      benchItems: ["Un teléfono en la mano de quien viaja", "Un aparato pequeño para quien inspecciona dentro del vehículo", "Una pantalla de escritorio para el equipo de noche"],
      benchSlots: ["Quien viaja, consultando un pase", "Quien inspecciona, en un autobús en marcha", "El equipo de noche, con teclado y un turno largo"],
      caseOrg: "City Hopper",
      caseFile: "CH-02",
      caseTitle: "Un pase, tres puertas",
      caseSituation: [
        "City Hopper quiere que viajeros, inspección y el turno de noche confíen en el mismo pase. Un proveedor ofrece tres aplicaciones separadas, cada una con su base de datos, porque así la demostración es más rápida.",
        "Quienes las usan no son desarrolladores. Quien viaja tiene prisa. Quien inspecciona está de pie en un pasillo. El turno de noche tiene tiempo, teclado y el trabajo de corregir errores.",
      ],
      caseTask: "Elige las puertas y rechaza un diseño en el que las tres aplicaciones puedan contradecirse.",
      caseSteps: [
        "Anota los tres trabajos y dónde está cada persona.",
        "Marca lo que debe ser idéntico: el pase, si vale y quién puede cambiarlo.",
        "Responde las decisiones.",
        "En la nota, di qué puerta es fina y por qué una segunda copia del pase sería un fallo.",
      ],
      decisions: [
        { prompt: "¿Dónde se encuentra quien viaja con el pase?", options: ["Solo una tarjeta de papel", "Una página de teléfono", "Tiene que ir a la oficina"] },
        { prompt: "¿Qué permanece igual entre las puertas?", options: ["El color de cada aplicación", "El registro del pase y las reglas", "El lema de la pantalla de inicio"] },
        { prompt: "El proveedor ofrece tres aplicaciones con tres bases de datos. ¿Qué haces?", options: ["Las aceptas, para que la demostración sea rápida", "Exiges un solo registro detrás de las puertas", "No construyes nada hasta el año que viene"] },
      ],
      noteLabel: "Tu nota para la dirección del transporte",
      noteHint: "Nombra las tres puertas y el único registro que deben compartir.",
    },
    design: {
      title: "Diseño para las personas",
      promise: "Empezar por la tarea que una persona cansada intenta terminar, no por la pantalla que quieres dibujar.",
      objectives: ["Describir una tarea antes de describir una pantalla.", "Escribir un error que diga qué hacer después.", "Notar cuándo un diseño solo funciona para quien está descansado y es experto."],
      start: [
        "Diseño, aquí, es la forma de la tarea, no una capa de pintura. Una persona llega con un trabajo: renovar una ayuda, pedir hora con una enfermera, ver si un puesto está abierto. Puede ser nueva, estar cansada, ir con prisa o usar solo el teclado. El sistema debe ayudarla a terminar.",
        "Si empiezas por los colores, el logotipo o la forma de la base de datos, construirás algo que tiene sentido para quien lo hace y no para quien lo usa. Pregunta qué intenta hacer, con sus palabras, antes de preguntar cómo se ve la pantalla.",
      ],
      how: [
        "Escribe la tarea en pasos que se puedan decir en voz alta. Un paso pide una cosa. Cada paso tiene vuelta atrás. Una pantalla vacía dice qué hacer, no solo que no hay nada. Un error dice qué falló y la acción siguiente, en palabras llanas, sin un número de código como única pista.",
        "Prueba los pasos como tres personas: alguien nuevo, alguien cansado al final del turno y alguien que no usa ratón. Si una se atasca, el diseño no está terminado. Lee las palabras en voz alta. Si no se las dirías a una persona en un mostrador, no las pongas en la pantalla.",
      ],
      expert: [
        "Los requisitos son las promesas: qué debe ser verdad cuando la persona termina, qué no debe ocurrir nunca y qué puede esperar. Una página de cara al público y la página del personal pueden verse distintas y servir a una sola promesa. El personal necesita rapidez y completitud. La página pública necesita calma y un camino corto.",
        "Un buen diseño deja rastro. Si una tarea se corta a la mitad, la persona no debería perder el trabajo, y un colega debería ver dónde se detuvo. Eso es diseño para la operación, no decoración.",
      ],
      example: [
        "La pregunta pública de Harbor Market es pequeña: ¿qué está abierto esta noche? La primera pantalla responde eso, con el nombre del puesto y el horario. No empieza por una cuenta, un mapa de la base de datos ni doce filtros.",
        "Quien marca su puesto como cerrado recibe una pregunta y una línea clara de guardado. Si la red cae, la página dice que el cambio aún no está guardado y qué hacer. No muestra un código de error en bruto.",
      ],
      narration:
        "Empieza por la tarea, no por la pantalla. Pregunta qué intenta terminar la persona, con sus palabras. Un paso debe pedir una sola cosa. Un error debe decir qué hacer después. En Harbor Market la pregunta pública es simple: ¿qué está abierto esta noche? La primera pantalla responde eso, antes de pedir nada más.",
      checkPrompt: "¿Qué diseñas primero?",
      checkOptions: ["La paleta de colores", "La tarea que la persona intenta terminar", "El logotipo", "La forma de la base de datos"],
      benchTitle: "Un formulario para alguien cansado",
      benchPrompt: "La renovación de Prestaciones Cívicas pide hoy doce preguntas en una pantalla. Elige la versión que una persona cansada puede terminar.",
      benchItems: ["Dejar los doce campos en una pantalla para que parezca completo.", "Preguntar de una en una, con vuelta atrás, y guardar sobre la marcha.", "Sustituir las palabras por dibujos y quitar las preguntas."],
      benchSlots: [],
      caseOrg: "Prestaciones Cívicas",
      caseFile: "CB-03",
      caseTitle: "La renovación de doce campos",
      caseSituation: [
        "La gente renueva una prestación una vez al año. El formulario actual tiene doce campos, dos de ellos códigos que la oficina entiende y el residente no. Si se equivoca en uno, la página dice «Error 422» y borra el formulario.",
        "Los residentes no son desarrolladores. Muchos están en el teléfono. Algunos usan solo el teclado. La oficina quiere menos renovaciones a medias, no un logotipo más bonito.",
      ],
      caseTask: "Reescribe el camino para que una persona pueda terminarlo, también cuando se equivoca.",
      caseSteps: ["Di la tarea del residente en una frase, con sus palabras.", "Corta el camino en pasos que pidan una cosa.", "Decide cómo habla un error y cómo termina alguien sin ratón.", "En la nota, escribe los tres primeros pasos tal como los vería el residente."],
      decisions: [
        { prompt: "¿Qué fijas antes de la pantalla?", options: ["El color de la cabecera", "La tarea con las palabras del residente", "El logotipo"] },
        { prompt: "La renovación no pasa una comprobación. ¿Qué dice la página?", options: ["Error 422, y el formulario se borra", "Qué falló y qué hacer después, conservando las respuestas", "Una página en blanco"] },
        { prompt: "¿Quién debe poder terminar?", options: ["Solo quien usa ratón", "Una persona con solo teclado, también si es nueva o está cansada", "Solo quien imprime el formulario"] },
      ],
      noteLabel: "Los tres primeros pasos, con las palabras del residente",
      noteHint: "Escribe los pasos que una persona vería de verdad, incluido lo que dice un error.",
    },
    tiers: {
      title: "Tres salas",
      promise: "Separar lo que la persona ve, lo que decide y lo que recuerda.",
      objectives: ["Nombrar el navegador, la aplicación y la base de datos con palabras llanas.", "Seguir una petición desde un toque hasta un registro guardado.", "Decir qué le pide a cada sala el hecho de tener que seguir funcionando un martes por la noche."],
      start: [
        "Casi todos los sistemas que miran a una persona y además guardan registros se organizan en salas. La primera es lo que la persona ve, a menudo un navegador. La segunda decide: comprueba quién es y aplica las reglas. La tercera recuerda: la base de datos, y a veces una copia de respuestas que te puedes permitir repetir.",
        "Puedes dibujarlo para una clínica, un mercado o un juego. Los nombres siguen sirviendo. Mezclar las salas es como un sistema acaba siendo algo que solo su autor puede sostener en la cabeza.",
      ],
      how: [
        "Una petición viaja. La persona toca «cerrado esta noche». El navegador envía ese deseo a la aplicación. La aplicación comprueba que esta persona puede cambiar este puesto y pide a la base de datos que lo recuerde. La base escribe la fila. La aplicación se lo dice al navegador, que muestra un «guardado» tranquilo.",
        "Operar significa que esto sigue ocurriendo un martes por la noche, cuando quien lo escribió duerme. Cada sala necesita un trabajo que se pueda vigilar. El navegador no debe ser el único lugar donde vive una regla, porque una persona puede cambiar su propio navegador. La base de datos no inventa la política. Guarda lo que la aplicación pidió, con cuidado.",
      ],
      expert: [
        "Las cachés y las colas son salas extra que añades cuando sabes por qué. Una caché recuerda una respuesta que puede tener unos segundos, como la lista pública de puestos abiertos. No debe ser la única memoria de un pago. Una cola guarda trabajo que puede esperar un momento, para que un pico no tire la sala que decide.",
        "Dibuja las salas antes de poner nombres de producto. Los productos cambian. La pregunta no: ¿dónde se toma esta decisión, dónde se recuerda y qué pasa si una sala cae? Si no puedes señalar la sala, no puedes operar el sistema.",
      ],
      example: [
        "En Harbor Market el tablón público es la sala del navegador. La sala de la aplicación decide si este puesto puede editar este puesto. La sala de la base recuerda el horario. Una caché puede guardar la lista pública unos segundos. No guarda la única copia de un cambio.",
        "Si la aplicación está caída, el tablón debe decirlo, no inventar horarios. Si la base está caída, la aplicación debe negar la escritura y decir que no se guardó. El silencio parecería un éxito.",
      ],
      narration:
        "Imagina tres salas. El navegador es lo que ve una persona. La aplicación decide, también quién puede actuar. La base de datos recuerda. Un toque viaja de la primera a la segunda y luego a la tercera. En Harbor Market el tablón público no debe inventar horarios si la sala que decide está caída. Un cambio guardado tiene que llegar a la sala que recuerda.",
      checkPrompt: "¿Dónde debe vivir la decisión «puede esta persona cambiar este puesto»?",
      checkOptions: ["Solo en el navegador", "En la aplicación, donde corren las reglas", "Solo en la base de datos", "En un cartel de papel"],
      benchTitle: "Etiqueta las salas",
      benchPrompt: "Une cada frase con la sala que debe poseerla.",
      benchItems: ["El navegador, lo que la persona ve", "La aplicación, que aplica las reglas", "La base de datos, que recuerda"],
      benchSlots: ["Mostrar la lista de puestos abiertos", "Decidir si esta persona puede editar este puesto", "Recordar el horario cuando la persona ya se fue"],
      caseOrg: "Harbor Market",
      caseFile: "HM-04",
      caseTitle: "El libro de puestos y el tablón público",
      caseSituation: [
        "Harbor Market quiere un tablón público de quién está abierto y una forma de que cada puesto actualice su horario desde el teléfono. La oficina es pequeña. Nadie allí escribe software. Aun así el tablón tiene que ser verdadero un sábado por la noche.",
        "Un amigo del mercado ofrece «ponerlo todo en la página», reglas incluidas, porque así hay menos piezas que alojar.",
      ],
      caseTask: "Nombra las tres salas y rechaza un diseño que esconda las reglas solo en el navegador.",
      caseSteps: ["Dibuja tres cajas: lo que la gente ve, lo que decide, lo que recuerda.", "Coloca el tablón público, la regla de «puede editar» y los horarios en esas cajas.", "Di qué debe hacer el tablón si la sala que decide está caída.", "En la nota, explica el camino de un cambio, desde el pulgar en un teléfono hasta una fila que sigue allí por la mañana."],
      decisions: [
        { prompt: "¿Dónde vive «puede este puesto editar este puesto»?", options: ["Solo en la página del teléfono", "En la aplicación, con las demás reglas", "En un cartel de la oficina"] },
        { prompt: "¿Dónde se recuerdan los horarios?", options: ["Solo en el navegador hasta que se cierra", "En la aplicación, en memoria, hasta un reinicio", "En la base de datos"] },
        { prompt: "¿Qué hace el tablón público mientras la sala que decide está caída?", options: ["Dice que el tablón en vivo no está disponible", "Inventa horarios para que la página no esté vacía", "Pide a quien compra que edite los puestos"] },
      ],
      noteLabel: "El camino de un cambio",
      noteHint: "Sigue a un puesto que cierra por la noche, desde el teléfono hasta el registro que sigue allí por la mañana.",
    },
    integration: {
      title: "La lista que se ejecuta sola",
      promise: "Dejar que una máquina repita las comprobaciones cada vez, y que se detenga si fallan.",
      objectives: ["Explicar qué hace la integración continua, con palabras que un colega pueda reutilizar.", "Nombrar qué comprueba un proceso antes de que la gente comparta un cambio.", "Decir qué significa un resultado rojo en una noche que importa."],
      start: [
        "La integración continua significa que el equipo junta los cambios a menudo y que una lista se ejecuta sola cada vez. La lista repite las mismas comprobaciones cada vez, de modo que una tarde ocupada y una mañana tranquila dan el mismo resultado. Construye el trabajo, ejecuta las pruebas y a veces busca secretos que no deberían estar en los archivos. Las personas siguen leyendo el resultado. La máquina hace la repetición.",
        "Sin esto, la primera vez que descubres un cambio roto es delante de una persona que necesitaba el sistema. Con esto, descubres la rotura mientras el cambio aún es pequeño.",
      ],
      how: [
        "Un proceso es esa lista escrita para que una máquina pueda ejecutarla. Un orden típico: alguien hace un cambio, la lista corre, una segunda persona mira y solo entonces el cambio se une a la línea compartida. Si la lista falla, el cambio no se une. La pantalla se pone roja. Rojo significa todavía no: el cambio no entra en la línea compartida hasta que la lista pasa.",
        "Lo que pones en la lista depende de la promesa. Un portal de notas se preocupa de que las sumas cuadren y de que un estudiante no vea las notas de otro. Un mercado se preocupa de que un extraño no edite un puesto. Escribe las promesas como comprobaciones. Una lista que solo mira el color de un botón es teatro.",
      ],
      expert: [
        "El proceso debe ser el mismo en la mañana de quien desarrolla y en la noche anterior a un día público. Si la gente puede saltárselo cuando tiene prisa, la prisa es justo cuando hacía falta. Protege el salto. Que sea raro, con nombre y escrito.",
        "Los registros de la lista no son un diario para secretos. Contraseñas, claves y datos personales no pertenecen a la salida. Una construcción verde que imprimió un secreto es un fallo, aunque esté verde.",
      ],
      example: [
        "La lista de Harbor Market corre cuando se ofrece un cambio del personal. Comprueba que el proyecto sigue construyéndose, que un extraño no puede editar un puesto y que el tablón público sigue respondiendo «¿qué está abierto?». Luego mira una segunda persona.",
        "La mañana de una fiesta, una lista roja detiene el cambio. El mercado abre con la versión de ayer que se sabía buena. Ese es el sentido de la máquina: está dispuesta a ser impopular.",
      ],
      narration:
        "La integración continua significa que una lista corre cada vez que el trabajo cambia. La máquina construye, comprueba y se detiene si algo que le importa a la promesa ha fallado. Rojo significa todavía no. En Harbor Market una lista roja la mañana de una fiesta mantiene delante del público la versión de ayer que funcionaba.",
      checkPrompt: "El resultado de una lista está en rojo. ¿Qué significa?",
      checkOptions: ["Se publica: el color es solo un adorno", "No se continúa. Algo que le importa a la lista ha fallado", "Se ignora si el cambio es pequeño", "Se celebra: el rojo significa listo"],
      benchTitle: "Ordena el proceso",
      benchPrompt: "Pon estos pasos en el orden que mantiene un mal cambio fuera de la línea compartida.",
      benchItems: ["Alguien hace un cambio.", "La lista se ejecuta sola.", "Una segunda persona mira.", "El cambio se une a la línea compartida."],
      benchSlots: [],
      caseOrg: "Escuela del Norte",
      caseFile: "NS-05",
      caseTitle: "La noche antes del día de notas",
      caseSituation: [
        "La Escuela del Norte publica las notas por la mañana. El portal muestra a cada estudiante solo las suyas. A las 21:00 de la víspera se ofrece un cambio bienintencionado del diseño. Quien lo hizo está seguro de que es diminuto.",
        "Familias y estudiantes no son desarrolladores. Un total mal sumado, o un estudiante viendo las notas de otro, no es un asunto cosmético.",
      ],
      caseTask: "Diseña la lista de esa noche, incluido quién puede dejar pasar un cambio.",
      caseSteps: ["Escribe las promesas que la lista debe proteger: los totales y la privacidad.", "Ordena los pasos, incluida una segunda persona.", "Decide qué pasa si la lista está roja a las 21:00.", "En la nota, di qué usa la mañana si el cambio no está listo."],
      decisions: [
        { prompt: "La lista está roja a las 21:00. ¿Qué pasa con el cambio?", options: ["Sale, porque la mañana de notas no puede esperar", "Se bloquea. La mañana usa la última versión que pasó", "Se saltan las comprobaciones, solo esta vez"] },
        { prompt: "¿Quién puede dejar que un cambio se una a la línea compartida?", options: ["Solo quien lo escribió", "Quien lo escribió y una segunda persona, después de que la lista esté verde", "Nadie: los cambios se copian a mano"] },
        { prompt: "Una comprobación imprime una contraseña de la base en su registro. ¿Qué es eso?", options: ["Útil, para que la siguiente persona pueda entrar", "Un fallo. Los secretos no pertenecen al registro", "Algo para enviar por correo a todo el personal"] },
      ],
      noteLabel: "Qué usa la mañana de las notas",
      noteHint: "Di qué corre por la mañana si el cambio de la noche está en rojo, y qué promesas guarda la lista.",
    },
    deployment: {
      title: "Publicar con cuidado",
      promise: "Poner un cambio delante de la gente en un paso pequeño, con camino de vuelta.",
      objectives: ["Distinguir una prueba del sistema real.", "Planear una publicación que se pueda deshacer.", "Decir quién debe oír qué cambió."],
      start: [
        "Publicar es llevar un cambio del banco de trabajo a un lugar que usa gente real. Suele haber un lugar privado para probarlo, un lugar de ensayo que se parece al real y el sistema real. El sistema real es aquel en el que una persona confía un martes por la noche.",
        "Una publicación es el momento en que el cambio cruza a ese lugar real. Las publicaciones grandes se sienten valientes y fallan con ruido. Las pequeñas, con camino de vuelta, se sienten quietas y son la forma de trabajar de los equipos cuidadosos.",
      ],
      how: [
        "Un camino de vuelta significa que puedes volver a la versión anterior sin reconstruirla de memoria. Lo ensayaste. Sabes cuánto tarda. Sabes qué pasa con el trabajo que la gente hizo durante la versión nueva, si lo hubo.",
        "Cuéntaselo a quienes van a encontrarse el cambio. Enfermeras, mostrador, puestos. No necesitan un diario técnico. Necesitan: qué cambió, qué hacer si se ve mal y a quién llamar. Una publicación en silencio es como un turno de noche pierde la confianza.",
      ],
      expert: [
        "Un interruptor de función permite encender un cambio primero para pocas personas. Es útil y también es una sala que hay que ordenar. Un interruptor dejado un año es un segundo sistema escondido dentro del primero. Nombra un dueño y una fecha para quitarlo.",
        "Nunca publiques solo porque el calendario lo dice. El viernes por la tarde, la noche antes de las notas, la hora en que abre el mercado: ahí es cuando más importa el camino de vuelta. Si no puedes volver atrás, no estás listo, por muy verde que estuviera la lista.",
      ],
      example: [
        "Harbor Market enciende una línea nueva de «cierra pronto» primero en una fila de puestos. La oficina mira el tablón una hora. El camino de vuelta es un interruptor al tablón de ayer, ya ensayado.",
        "Los puestos lo oyen en la nota de la mañana: qué verán y que los horarios no cambian. La publicación no es una sorpresa soltada a la hora de abrir.",
      ],
      narration:
        "Publicar es el momento en que un cambio llega a personas que no lo hicieron. Guarda un lugar privado, un lugar de ensayo y el sistema real. Publica en un paso pequeño y conserva un camino de vuelta que de verdad hayas probado. Di al turno qué cambió y a quién llamar. Una publicación en silencio es como se pierde la confianza.",
      checkPrompt: "¿Qué debes tener antes de que un cambio llegue al sistema real?",
      checkOptions: ["Un viernes por la tarde, para tener el fin de semana", "Un camino de vuelta a la versión anterior", "El cambio más grande posible, para hacerlo solo una vez", "Silencio, para que nadie se preocupe"],
      benchTitle: "Elige la publicación",
      benchPrompt: "Santa Brígida quiere una forma nueva de que las enfermeras cambien un turno. ¿Qué publicación te fías?",
      benchItems: ["Sustituir todo el cuadrante el lunes al empezar el turno, sin camino de vuelta.", "Encender el cambio nuevo en una sola planta y conservar un regreso ensayado al cuadrante antiguo.", "Encenderlo para todo el mundo a medianoche y no decírselo a nadie."],
      benchSlots: [],
      caseOrg: "Hospital Santa Brígida",
      caseFile: "SB-06",
      caseTitle: "El cuadrante de la planta",
      caseSituation: [
        "Las enfermeras de Santa Brígida cambian turnos en un cuadrante. Un botón nuevo de cambio ha pasado las comprobaciones. La planta está llena. Quienes usan el cuadrante están cansados y no son desarrolladores.",
        "Si el botón nuevo deja un turno sin enfermera, el camino de vuelta importa más que el botón.",
      ],
      caseTask: "Planea la publicación: de qué tamaño, cómo vuelves y a quién se lo dices.",
      caseSteps: ["Nombra el sistema real y quién está delante.", "Elige un primer paso pequeño, no todo el hospital a la vez.", "Escribe el camino de vuelta en una frase que pueda seguir quien coordina la noche.", "En la nota, redacta el mensaje que la planta va a leer de verdad."],
      decisions: [
        { prompt: "¿De qué tamaño es la primera publicación?", options: ["Todas las plantas, el lunes por la mañana", "Una planta, y el resto sin cambios", "Una publicación secreta, para que no haya jaleo"] },
        { prompt: "¿Hay camino de vuelta?", options: ["No. Volver llevaría una semana de reconstrucción", "Sí. Está ensayado y alguien de la noche puede empezarlo", "Confiamos en no necesitarlo"] },
        { prompt: "¿Quién oye qué cambió?", options: ["Nadie, para evitar preguntas", "Las enfermeras y la coordinación, en palabras llanas, con un nombre al que llamar", "Solo un cartel en el aparcamiento"] },
      ],
      noteLabel: "La nota que leerá la planta",
      noteHint: "Di qué cambió, qué hacer si se ve mal y a quién llamar.",
    },
    maintain: {
      title: "La persona que llega después",
      promise: "Dejar el sistema para que alguien que llega en seis meses pueda cambiar una cosa con seguridad.",
      objectives: ["Explicar el mantenimiento como cuidado de la persona siguiente.", "Separar un cambio pequeño del núcleo peligroso.", "Nombrar un dueño para la parte que llama a alguien por la noche."],
      start: [
        "Mantenible significa que una persona que no construyó el sistema aún puede cambiarlo sin romper la promesa. Esa persona puedes ser tú, dentro de seis meses, cuando hayas olvidado la parte ingeniosa. Puede ser un colega nuevo. Puede ser un voluntario en una asociación.",
        "Si cada cambio exige al autor original, el sistema ya está fallando, aunque hoy se vea bien.",
      ],
      how: [
        "Los nombres deben decir para qué sirve una cosa. Las piezas deben ser lo bastante pequeñas para tenerlas en la cabeza. Un mapa, escrito, dice dónde va un cambio: la carta de agradecimiento está aquí, el pago está allí, y se encuentran en una puerta. La persona siguiente cambia la carta sin abrir el pago.",
        "La propiedad forma parte del mapa. Cuando el pago falla de noche, llama un rol con nombre, no «quien ande por ahí». El mapa incluye cómo ejecutar las comprobaciones, dónde está el historial y qué no se improvisa nunca.",
      ],
      expert: [
        "La ingeniosidad que solo el autor puede leer es un coste, no un regalo. Prefiere una estructura que una persona nueva pueda seguir. Los comentarios explican el porqué, no lo que la línea siguiente ya dice. Interruptores muertos, puertas sin uso y copias de la misma regla en tres sitios son deuda de mantenimiento.",
        "Un sistema para quienes no desarrollan necesita mantenedores que puedan rechazar un enredo. «¿Puede una persona nueva cambiar la carta con seguridad?» es una pregunta de publicación, no un adorno.",
      ],
      example: [
        "Harbor Market escribe un mapa de una página. El horario es una pieza. Quién puede editar un puesto es otra. Los pagos de luz y agua, si se añaden más tarde, se quedan aparte de las palabras públicas del tablón.",
        "Alguien nuevo del sábado puede cambiar un cierre por festivo desde el mapa, ejecutar la lista y preguntar al dueño nombrado si entra en juego la regla de quién puede editar. No rebusca en un montón indiferenciado.",
      ],
      narration:
        "Mantenible significa que la persona siguiente puede cambiar una cosa con seguridad. Esa persona puedes ser tú, dentro de seis meses. Deja un mapa. Separa la carta de agradecimiento del pago. Nombra quién recibe la llamada de noche. En Harbor Market alguien nuevo del sábado puede cambiar un cierre festivo sin tocar la regla de quién puede editar un puesto.",
      checkPrompt: "¿Qué frase describe mejor un sistema mantenible?",
      checkOptions: ["Es ingenioso, y solo el autor puede cambiarlo", "Una persona nueva encuentra la pieza y la cambia sin romper el resto", "Usa siempre la moda más nueva", "Es el archivo más largo, así que todo está en un sitio"],
      benchTitle: "La carta de agradecimiento",
      benchPrompt: "Kindling es una asociación pequeña. La página de donativos y la carta de agradecimiento viven en un enredo. Un voluntario necesita cambiar la carta. ¿Qué eliges?",
      benchItems: ["Dejar la carta dentro del código de pago para que nada se desajuste.", "Separar la carta del pago, con una puerta entre ambos y un mapa corto.", "Reescribir todo el sitio de la asociación antes de poder cambiar la carta."],
      benchSlots: [],
      caseOrg: "Kindling",
      caseFile: "KL-07",
      caseTitle: "La página de donativos enredada",
      caseSituation: [
        "El sitio de Kindling recibe donativos y envía una carta de agradecimiento. Los dos crecieron en un montón de archivos. Un voluntario que no es desarrollador quiere cambiar la carta para el invierno. La última vez que alguien lo intentó, los pagos con tarjeta fallaron una tarde.",
        "La asociación no puede contratar un equipo grande. Sí puede dejar un mapa y una frontera.",
      ],
      caseTask: "Propón una separación para que la carta pueda cambiar sin arriesgar el pago.",
      caseSteps: ["Nombra los dos trabajos: palabras cálidas y cobrar con seguridad.", "Pon una frontera entre ellos.", "Nombra a quién se llama si los pagos fallan.", "En la nota, escribe el mapa en pocas líneas que un voluntario pueda seguir."],
      decisions: [
        { prompt: "¿Dónde debe vivir la carta de agradecimiento?", options: ["Dentro del código de pago", "Aparte del pago, encontrándose en una puerta", "Congelada, para que nadie cambie las palabras"] },
        { prompt: "¿A quién se llama si los pagos fallan de noche?", options: ["A quien casualmente lo vea", "A un rol con nombre, escrito en el mapa", "A todo el chat de voluntarios, a la vez"] },
        { prompt: "¿Dónde vive el mapa?", options: ["En la memoria del autor original", "Escrito, junto a cómo ejecutar las comprobaciones", "En un chat privado que desaparece"] },
      ],
      noteLabel: "El mapa para un voluntario nuevo",
      noteHint: "Muestra dónde está la carta, dónde está el pago y a quién llamar.",
    },
    scale: {
      title: "Cuando la cola se alarga",
      promise: "Crecer en número de personas sin romper lo que debe seguir siendo exacto.",
      objectives: ["Distinguir un momento de mucha gente de un diseño simplemente derrochador.", "Explicar una cola y una caché sin esconder el intercambio.", "Proteger la exactitud y la equidad mientras creces."],
      start: [
        "La escala es lo que ocurre cuando llega más gente de la que la forma actual puede sostener. Diez personas en una clínica no son un millón comprando una entrada en el mismo segundo. Las dos cosas son reales. La primera no necesita la maquinaria de la segunda. La segunda se cae si finges que es la primera.",
        "Lo que debe seguir siendo verdad no puede ser aproximado. A una persona se le cobra una vez. Un asiento se vende una vez. Un pase vale o no vale. Las páginas bonitas pueden esperar. El registro exacto no.",
      ],
      how: [
        "Cuando llega una multitud, forma una fila. Una cola es esa fila para el trabajo. A cada persona le parece más lenta y evita que la sala que decide se caiga. Una caché repite una respuesta pública que puede tener unos segundos, para no preguntar a la base un millón de veces lo mismo. Una copia de un servicio puede repartir el trabajo de solo lectura. Las copias no perdonan una regla que solo era verdad en una máquina.",
        "La equidad forma parte de la escala. Quien tiene una conexión más rápida no debería poder colarse en una fila que prometiste justa. Escribe qué significa «justo» antes de que llegue la multitud, no durante ella.",
      ],
      expert: [
        "El orden es: medir el dolor real, proteger el registro exacto y luego añadir una cola o una caché en la parte que puede ceder. No guardes en caché un pago. No dejes que la página pública golpee la fila que debe ser exacta. No compres una máquina más grande como única idea, o la comprarás otra vez el año que viene.",
        "Millones de personas a la vez es una promesa concreta. Necesita un número, un ensayo y un plan para el minuto en que el número se supera. «Ya saldrá bien» no es una arquitectura.",
      ],
      example: [
        "El sábado normal de Harbor Market no necesita la maquinaria de una fiesta. La noche de fiesta sí. El tablón público puede ir unos segundos atrasado. Marcar un puesto como cerrado, y cualquier pago, sigue siendo exacto y pasa por una fila si la multitud es grande.",
        "Quien compra puede ver «abierto» un momento después de que un puesto cierre. Nunca se le debe cobrar dos veces, y dos personas no deben oír que tienen la misma última ración si el mercado vende entradas numeradas.",
      ],
      narration:
        "La escala significa más gente de la que la forma actual puede sostener. Diez personas y un millón son problemas distintos. Lo que debe ser exacto, sigue exacto: se cobra una vez, se vende un asiento una vez. Una cola es una fila que protege la sala que decide. Una caché puede repetir una respuesta pública unos segundos. No debe recordar un pago. En Harbor Market el tablón puede ir un poco atrasado. El dinero, no.",
      checkPrompt: "Mientras un sistema crece, ¿qué debe seguir siendo verdad?",
      checkOptions: ["Las páginas se ponen más bonitas", "Las promesas exactas, como cobrar a una persona una sola vez", "La marca se oye más fuerte", "Las herramientas son las más nuevas"],
      benchTitle: "La noche de la fiesta",
      benchPrompt: "Un millón de personas intentará comprar una entrada del Festival de los Faroles a las 10:00. ¿Qué proteges primero?",
      benchItems: ["Un logotipo más grande y una animación más rápida.", "El registro exacto: una entrada, una venta, ningún cobro doble. La página pública espera en una fila.", "Una galería más bonita de los faroles del año pasado."],
      benchSlots: [],
      caseOrg: "Festival de los Faroles",
      caseFile: "LF-08",
      caseTitle: "Entradas a las 10:00",
      caseSituation: [
        "El Festival de los Faroles vende un número limitado de entradas. El año pasado la página se congeló a las 10:00 y a algunas personas se les cobró dos veces. El público no es un equipo técnico. Volverá a tocar si la página parece atascada.",
        "Tienes días normales y tienes este minuto. No deben diseñarse como el mismo minuto.",
      ],
      caseTask: "Di qué proteges primero, qué puede esperar en una fila y qué no guardarás en caché.",
      caseSteps: ["Nombra la promesa exacta: una entrada, un cobro.", "Di qué ve la persona mientras espera, para que no toque dos veces por pánico.", "Decide qué se puede guardar en caché y qué no.", "En la nota, escribe el orden de acciones de ese minuto."],
      decisions: [
        { prompt: "¿Qué proteges primero?", options: ["Una página más bonita", "Una entrada y un cobro, con exactitud", "Una película nueva de marca"] },
        { prompt: "¿Cómo se encuentra la multitud con la sala de venta?", options: ["Cada toque golpea la fila de pago de inmediato, con toda la fuerza", "Una cola, con un estado de espera claro", "Cierras el sitio y vendes solo por correo"] },
        { prompt: "¿Qué se puede guardar en caché?", options: ["El propio pago", "Una pista pública, como si aún quedan entradas, con unos segundos de retraso", "Nada, ni las imágenes estáticas"] },
      ],
      noteLabel: "El minuto de las 10:00",
      noteHint: "Escribe el orden: qué sigue exacto, qué espera y qué ve la persona.",
    },
    observe: {
      title: "Ver el sistema",
      promise: "Saber qué preguntas hacer cuando algo se ve mal, y qué alertas puede atender una persona.",
      objectives: ["Separar un registro, una métrica y un rastro con palabras llanas.", "Seguir una petición desde la puerta hasta el dato.", "Escribir una alerta que diga a un humano qué hacer."],
      start: [
        "Observar significa poder decir qué está haciendo el sistema sin adivinar. Cuando una persona dice «el tablón está mal», necesitas una forma de mirar que no dependa de que el autor original esté despierto.",
        "Tres preguntas cubren casi todas las noches. ¿Qué hizo esta petición? ¿Cuántas están fallando? ¿Qué escribió el sistema en ese momento?",
      ],
      how: [
        "Un registro es una línea de diario: a esta hora, este puesto se marcó cerrado, por este tipo de actor. No debe contener secretos ni el dato privado de una persona más allá de lo que la noche exige. Una métrica es un número en el tiempo: cuántas cargas del tablón fallaron en cinco minutos. Un rastro es el camino de una petición por las salas, para ver dónde se detuvo.",
        "Una alerta es una métrica con una promesa: si este número cruza una línea, una persona nombrada debe hacer una cosa nombrada. Una alerta sobre la que nadie puede actuar es ruido, y el ruido enseña a ignorar la de verdad.",
      ],
      expert: [
        "Decide las preguntas antes de la caída. Una tarde tranquila, escribe: si los envíos dejan de mostrarse como «en reparto», ¿qué rastro abro, qué número creo, qué registro leo? Si inventas las preguntas a las 02:14, te saltarás la sala que de verdad falló.",
        "La salud es una frase, no un punto verde. «Sano» significa que el tablón público coincide con la base en unos segundos y que los guardados fallidos se ven. Un punto verde que esconde una cola atascada es como se pierde una noche con educación.",
      ],
      example: [
        "Harbor Market mira tres cosas. El número de guardados fallidos. La edad de la caché pública. Y, cuando un puesto dice «no se guardó», el camino de esa petición.",
        "La alerta es: si suben los guardados fallidos, despierta al dueño nombrado y detén más publicaciones. No le llama porque una imagen cargó despacio.",
      ],
      narration:
        "No puedes arreglar lo que no puedes ver. Un registro es una línea de diario. Una métrica es un número en el tiempo. Un rastro es el camino de una petición. Una alerta debe nombrar la acción que toma una persona. En Harbor Market, si los guardados empiezan a fallar, se despierta a un dueño nombrado y se paran las publicaciones. Una imagen lenta no llama a nadie.",
      checkPrompt: "Un puesto dice que el cambio no se guardó. ¿Qué quieres primero?",
      checkOptions: ["Esperar que fuera un caso suelto", "El camino de esa petición", "Un color nuevo en el punto de estado", "Reiniciar, antes de mirar"],
      benchTitle: "Une la pregunta",
      benchPrompt: "Parcel & Pine, 02:14. Los envíos han dejado de mostrarse como «en reparto». Une cada necesidad con la herramienta.",
      benchItems: ["Un rastro, el camino de una petición", "Una métrica, un número en el tiempo", "Un registro, el diario de lo que se escribió"],
      benchSlots: ["Seguir la actualización de un paquete por las salas", "Ver cuántas actualizaciones fallan", "Leer lo que el sistema escribió cuando un conductor marcó un paquete"],
      caseOrg: "Parcel & Pine",
      caseFile: "PP-09",
      caseTitle: "02:14, el estado se queda en silencio",
      caseSituation: [
        "Parcel & Pine muestra a los clientes un estado: preparado, en reparto, entregado. A las 02:14 las actualizaciones de «en reparto» se paran. Los conductores siguen trabajando. Los clientes actualizan y no ven nada nuevo. Quien opera de noche no es desarrollador.",
        "Estás escribiendo las preguntas que debería poder hacer, y la alerta que debería haber despertado a alguien.",
      ],
      caseTask: "Di qué miras, qué dice la alerta y qué no merece despertar a un humano.",
      caseSteps: ["Escribe las tres preguntas: un paquete, cuántos, qué se escribió.", "Nombra la primera mirada: el camino de una actualización.", "Escribe la alerta como una acción, no como un estado de ánimo.", "En la nota, define «sano» en una frase que el operador pueda comprobar."],
      decisions: [
        { prompt: "¿Cuál es la primera mirada?", options: ["Reiniciarlo todo", "El camino de una actualización que debería haberse mostrado", "Esperar a la mañana por si se cura"] },
        { prompt: "¿Qué dice una buena alerta?", options: ["Algo se siente raro", "Las actualizaciones fallidas cruzaron la línea. Haz esto y llama a este rol", "Escribe a toda la empresa"] },
        { prompt: "Una sola foto de producto carga despacio. ¿Despiertas a quien opera de noche?", options: ["Sí, llama por cada imagen lenta", "No. Llama por las actualizaciones de estado fallidas, no por una imagen lenta", "Llámalo toda la noche, para que siga alerta"] },
      ],
      noteLabel: "Qué significa sano esta noche",
      noteHint: "Escribe la frase que un operador puede comprobar y la primera pregunta que hace.",
    },
    security: {
      title: "Quién, y qué puede hacer",
      promise: "Separar la identidad del permiso, y evitar que se escapen los datos privados.",
      objectives: ["Distinguir autenticación de autorización con palabras llanas.", "Nombrar tres formas comunes de que se escape un dato privado.", "Elegir el permiso más pequeño, a propósito."],
      start: [
        "La autenticación responde: ¿quién eres? La autorización responde: ¿qué puedes hacer? Un inicio de sesión prueba lo primero. No concede lo segundo. Un estudiante que puede entrar no debe por eso ver las notas de todos. Quien tiene un puesto y puede entrar no debe ver la caja del puesto de al lado.",
        "La seguridad de un sistema usado por quienes no desarrollan es sobre todo esta disciplina, más el cuidado de los secretos. La gente hará lo fácil. Lo fácil tiene que ser también lo seguro.",
      ],
      how: [
        "El camino entre el navegador y la aplicación va cifrado, para que un extraño en la red no pueda leer la página. Los secretos, como contraseñas y claves, viven fuera del proyecto y fuera de los registros. Cada persona tiene su propio acceso. Una contraseña compartida parece amable y hace que cada acción sea imposible de atribuir, e imposible de retirar cuando alguien se va.",
        "Los datos privados se escapan por errores ordinarios. Se ponen en la barra de direcciones, donde se copian y se registran. Se dejan en una copia de seguridad de un portátil. Se muestran a un rol que no los necesitaba. Se escriben en el registro de una lista. El menor privilegio significa que cada rol ve solo lo que el trabajo necesita.",
      ],
      expert: [
        "Las amenazas son concretas. Escribe: quién podría querer este registro, qué puede hacer ya y qué contaría como fuga. Un libro de notas se escapa si un estudiante ve las de otro, si un portátil perdido guarda la copia, o si se puede adivinar una dirección con el número de estudiante. No hace falta un guion de película.",
        "Las sesiones son cookies que guarda el navegador. Deben ser imposibles de robar por un script de otro sitio, caducar en un plazo razonable y ser inútiles si se copian a un registro. Los límites de ritmo impiden que un script pruebe un millón de contraseñas. Nada de eso sustituye la separación básica: quién eres y qué puedes hacer.",
      ],
      example: [
        "Harbor Market da a cada puesto su propio acceso. Pueden editar su puesto. No pueden abrir la caja del puesto de al lado. El rol de oficina sí. El público ve el horario y nada más.",
        "Una copia de seguridad del libro de puestos va cifrada y la guarda el dueño nombrado, no un portátil personal en una bolsa. La dirección de una página no contiene nunca un total privado.",
      ],
      narration:
        "La autenticación pregunta quién eres. La autorización pregunta qué puedes hacer. Entrar no es un permiso para verlo todo. Da a cada persona su propio acceso. Mantén los secretos fuera del proyecto y fuera de los registros. Los datos privados se escapan por la barra de direcciones, por copias en portátiles y por roles que ven demasiado. En Harbor Market un puesto ve el suyo, no la caja de al lado.",
      checkPrompt: "¿Qué afirmación es correcta?",
      checkOptions: ["Autenticación y autorización son dos palabras para lo mismo", "La autenticación dice quién eres. La autorización dice qué puedes hacer", "Una contraseña larga es toda la seguridad", "Esconder la página equivale a un permiso"],
      benchTitle: "¿Qué diseños se escapan?",
      benchPrompt: "El libro de notas del Colegio Westfield. Elige los tres diseños que se escapan. Deja en paz los tres más seguros.",
      benchItems: [
        "Una contraseña compartida para todo el profesorado, escrita en la sala de personal",
        "Las notas de un estudiante puestas en la barra de direcciones",
        "La copia nocturna copiada al portátil personal de un profesor",
        "Cada profesor y cada estudiante tiene su propio acceso",
        "La copia está cerrada, y solo un rol nombrado puede abrirla",
        "Un estudiante ve sus notas, y un profesor ve su propia clase",
      ],
      benchSlots: [],
      caseOrg: "Colegio Westfield",
      caseFile: "WC-10",
      caseTitle: "El libro de notas",
      caseSituation: [
        "Westfield guarda las notas de cada estudiante. El profesorado las introduce. Cada estudiante consulta las suyas. Una demostración del proveedor usa una contraseña para todo el personal, y el número de estudiante aparece en la dirección web para que sea fácil compartir un enlace.",
        "Los estudiantes son jóvenes. El personal va justo de tiempo. Tomarán el camino fácil. El camino fácil tiene que ser el que no se escapa.",
      ],
      caseTask: "Di quién puede ver qué, y cierra tres fugas.",
      caseSteps: ["Lista los roles: estudiante, profesor, oficina.", "Escribe qué puede ver cada rol y qué no debe ver.", "Marca la contraseña compartida, la barra de direcciones y la copia en el portátil como fugas a cerrar.", "En la nota, describe el diseño más seguro con palabras que pudiera aprobar un jefe de curso."],
      decisions: [
        { prompt: "¿Cómo entra la gente?", options: ["Una contraseña compartida en la sala de personal", "Cada persona tiene su propio acceso", "Sin acceso: la página es oscura"] },
        { prompt: "¿Quién ve las notas de un estudiante?", options: ["Cualquiera que pueda entrar", "El estudiante ve las suyas. Un profesor ve su clase. La oficina ve lo que su trabajo necesita", "Las notas son públicas, para ahorrar llamadas"] },
        { prompt: "¿Dónde vive la copia de seguridad?", options: ["En el portátil personal de un profesor", "Cerrada, abierta solo por un rol nombrado", "En el chat del personal"] },
      ],
      noteLabel: "El libro de notas más seguro",
      noteHint: "Di quién ve qué y cómo se cierran las tres fugas.",
    },
    futures: {
      title: "Qué cambia y qué se sostiene",
      promise: "Notar los cambios reales en cómo se construyen los sistemas, y negarte a apostar la promesa.",
      objectives: ["Nombrar cambios que de verdad llegan, sin las palabras de venta.", "Nombrar lo que no caduca: la tarea, el registro, el fallo, el cuidado.", "Preferir un futuro del que puedas salir."],
      start: [
        "Las herramientas, las plataformas y las modas cambian. Las personas siguen necesitando terminar una tarea, fiarse de un registro y recibir ayuda cuando falla. Una tendencia futura merece atención cuando cambia dónde corre el trabajo, quién guarda los datos o cómo pide algo una persona. No merece atención solo por ser nueva.",
        "Los sistemas para quienes no desarrollan seguirán necesitando una puerta de cara al público y un sistema de apoyo detrás. Ese apoyo puede sentarse un día más cerca de la persona, en un aparato, o más lejos, en un servicio compartido. La promesa tiene que sobrevivir a cualquiera de los dos movimientos.",
      ],
      how: [
        "Observa tres desplazamientos. El trabajo puede correr más cerca de la persona, de modo que un quiosco o un teléfono sostenga una promesa pequeña aunque caiga la red, y envíe el registro después. La organización que guarda los datos puede no ser la que la persona cree, así que importan los contratos y las salidas. Las personas pueden pedir con el habla ordinaria, lo que significa que el sistema sigue necesitando una tarea clara debajo de la conversación.",
        "Lo que se sostiene: diseñar desde la tarea, una decisión que vive en una sala conocida, una lista, un camino de vuelta, un mapa para la persona siguiente, un registro exacto, una forma de ver un fallo y una separación entre quién es alguien y qué puede hacer. Eso no caduca cuando caduca un proveedor.",
      ],
      expert: [
        "Una elección a prueba de futuro es una de la que puedes salir. ¿Puedes exportar el registro? ¿Puede otro equipo ejecutar las comprobaciones? ¿Puedes apagar la puerta nueva? Si la respuesta es no, no has comprado un futuro. Has alquilado una trampa. Escribe la salida el día que entras.",
        "No apuestes una escuela, una clínica, un mercado o un festival a un solo servicio de moda que no puedes inspeccionar y del que no puedes salir. Usa lo nuevo en el borde, donde un fallo se puede sobrevivir. Guarda el registro donde aún puedas leerlo dentro de diez años.",
      ],
      example: [
        "Harbor Market quizá deje un día que un puesto diga el horario en voz alta en lugar de tocarlo. La tarea no cambia: este horario, este puesto, esta persona autorizada a decirlo. El registro no cambia. La puerta hablada es una plataforma nueva delante de las mismas salas.",
        "Si el servicio de voz cerrara, la página del teléfono seguiría. Esa es la prueba. El mercado no guarda la única copia de sus horarios dentro de un servicio que no puede exportar.",
      ],
      narration:
        "Las herramientas cambiarán. La promesa no debería. Las personas siguen necesitando terminar una tarea, fiarse de un registro y recibir ayuda cuando falla. Puedes acercar el trabajo a la persona, o dejar que pregunte con el habla. Conserva una forma de salir. En Harbor Market una puerta hablada podría sentarse delante del mismo libro de puestos. Si esa puerta cerrara, el registro seguiría siendo suyo.",
      checkPrompt: "¿Qué no caduca?",
      checkOptions: ["La moda actual del proveedor", "La promesa a la persona: la tarea, el registro, el cuidado cuando falla", "La moda visual de este año", "Un lema sobre el futuro"],
      benchTitle: "Lo que conservas",
      benchPrompt: "La Sala Nacional de Lectura debe planear cinco años. ¿Qué postura tomas?",
      benchItems: ["Adoptar un lema y un solo proveedor, y poner allí la única copia del catálogo.", "Prepararte para cambiar de herramientas, y rechazar cualquier elección de la que no puedas salir. El catálogo sigue siendo exportable.", "Congelar todas las herramientas para siempre, de modo que nada nuevo pueda probarse en el borde."],
      benchSlots: [],
      caseOrg: "Sala Nacional de Lectura",
      caseFile: "NR-11",
      caseTitle: "Cinco años del catálogo",
      caseSituation: [
        "La Sala de Lectura presta al público y guarda un catálogo del que depende el personal. Un proveedor ofrece una puerta nueva y hermosa, con la condición de que el catálogo viva solo dentro de su servicio. Salir más tarde significaría perder la historia de los préstamos.",
        "Lectores y mostrador no son desarrolladores. Les gustará una puerta más simple. No les gustará un catálogo que no puedan recuperar.",
      ],
      caseTask: "Escribe qué conservas, qué te preparas a cambiar y qué te niegas a apostar.",
      caseSteps: ["Enuncia la promesa que debe seguir siendo verdad dentro de cinco años.", "Nombra una puerta nueva que estarías dispuesto a probar en el borde.", "Nombra la salida: cómo el catálogo se va contigo.", "En la nota, escribe el informe que de verdad darías al consejo."],
      decisions: [
        { prompt: "¿Qué conservas, hagan lo que hagan las herramientas?", options: ["La relación con el proveedor", "El catálogo y el registro de préstamos, legibles sin el proveedor", "El lema"] },
        { prompt: "¿Qué preparas?", options: ["Quedarte, aunque no puedas exportar", "Una forma de salir, probada, antes de depender de la puerta nueva", "Nada. Cinco años es demasiado lejos para planear"] },
        { prompt: "¿Qué rechazas?", options: ["Un diseño en el que la única copia vive en un servicio del que no puedes salir", "Cualquier puerta nueva, incluso una prueba pequeña", "Un informe escrito al consejo"] },
      ],
      noteLabel: "El informe al consejo",
      noteHint: "Di qué conservas, qué probarías y qué no vas a apostar.",
    },
  },
  brief: {
    title: "Harbor Market, de punta a punta",
    dek: "Un mercado. Once promesas. Un informe que una dirección puede leer.",
    situation: [
      "Has practicado las mismas ideas en una clínica, una empresa de autobuses, una escuela, un hospital, una asociación, un festival, una red de paquetes, un colegio y una biblioteca. Harbor Market es donde se encuentran.",
      "Quienes tienen un puesto no son desarrolladores. Quien compra tiene prisa. La oficina es pequeña. El tablón debe ser verdadero un sábado por la noche, y seguir siendo vuestro dentro de cinco años.",
    ],
    task: "Escribe el informe de operación: una elección por cada promesa, y una nota final con tus palabras.",
    steps: [
      "Lee tus notas anteriores en el dossier. Son la práctica. Esta página es el traslado.",
      "Responde cada promesa para Harbor Market, no para las otras organizaciones.",
      "Mantén a la vista el tablón público, el libro de puestos y las personas a la vez.",
      "En la nota final, di a una dirección nueva qué no se debe apostar nunca.",
    ],
    decisions: [
      { prompt: "¿Dónde vive el banco de trabajo del personal?", options: ["En un portátil que se va a casa", "En un banco compartido con historial", "En papel"] },
      { prompt: "¿Cómo se encuentran con el libro de puestos quien compra, quien tiene un puesto y la oficina?", options: ["Tres sistemas separados", "Tres puertas, un registro", "Solo una aplicación de teléfono, sin escritorio"] },
      { prompt: "¿Qué diseñas primero?", options: ["Las pantallas", "La tarea: qué está abierto y quién puede decirlo", "El logotipo"] },
      { prompt: "¿Dónde vive «puede esta persona editar este puesto»?", options: ["Solo en el navegador", "En la aplicación", "Solo en la base de datos"] },
      { prompt: "Una lista está roja la mañana de una fiesta. ¿Qué pasa?", options: ["Se publica el cambio más tarde de todos modos", "Se bloquea. Se abre con la última versión verde", "Se saltan las comprobaciones"] },
      { prompt: "¿Cómo publicas un cambio del tablón público?", options: ["Todo, a la hora de abrir", "Un paso pequeño, con un camino de vuelta ensayado", "En silencio"] },
      { prompt: "Alguien nuevo debe cambiar un cierre festivo. ¿Cómo está formado el sistema?", options: ["Un montón, pagos incluidos", "Las palabras aparte de lo que debe seguir exacto, con un mapa", "Congelado, para que nada pueda cambiar"] },
      { prompt: "En una noche de mucha gente, ¿qué sigue exacto?", options: ["La animación", "El registro de un cambio, y cualquier pago", "Nada: se cierra el mercado"] },
      { prompt: "Un puesto dice que un cambio no se guardó. ¿Qué quieres?", options: ["Esperanza", "El camino de esa petición, y una alerta sobre la que una persona pueda actuar", "Un reinicio inmediato como única herramienta"] },
      { prompt: "¿Quién ve las notas privadas de un puesto?", options: ["Cualquiera con la contraseña compartida de la oficina", "El puesto, y el rol de oficina que las necesita", "El público"] },
      { prompt: "Se ofrece una puerta hablada nueva. ¿Qué exiges?", options: ["La única copia de los horarios se muda a ese servicio", "Puedes salir. El registro sigue siendo exportable", "No se puede probar nunca una puerta nueva"] },
    ],
    noteLabel: "La nota para la dirección",
    noteHint: "Di qué no debe apostar nunca Harbor Market: el registro, las personas y el camino de vuelta.",
    narration:
      "Este es el mercado entero, en un informe. Quienes tienen un puesto no son desarrolladores. El tablón tiene que ser verdadero un sábado por la noche, y el registro tiene que seguir perteneciendo al mercado dentro de cinco años. Elige el banco compartido, un registro detrás de las puertas, una lista que pueda decir que no, una publicación pequeña con camino de vuelta, un mapa para la persona siguiente, un registro exacto cuando llega la multitud, una forma de ver un fallo, permisos que coincidan con el trabajo, y un futuro del que se pueda salir.",
  },
};
